### PR TITLE
Ported Cairo release info from existing starknet.io/docs

### PR DESCRIPTION
**Pull request by JameStark**
### Description of the Changes

Adding a page to track versions of StarkNet

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-136/documentation/useful_info/release_versions/

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/136)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/136)* status: all files reviewed, 6 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 11 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb6BK51OmCYTbccIXE:-NIb6BK51OmCYTbccIXF:b-pnzxdr) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L11)):*
> ```AsciiDoc
> 
> [id="versions"]
> == Upcoming version (v0.10.3-pre)
> ```

Is this a manual copy from the repo or something automatic? If the former, then let's just write 0.10.3 (the "-pre" tags are only there to have the package available for external teams before the testnets upgrade).
___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 13 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb5rPeCuA69GcRS05t:-NIb5rPeCuA69GcRS05u:b-emnuxq) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L13)):*
> ```AsciiDoc
> == Upcoming version (v0.10.3-pre)
> 
> This release is currently on StarkNet Goerli (testnets 1 and 2).
> ```

Replace with: This is the currently deployed version on StarkNet Testnets. The Mainnet environment upgrade is planned for December 12.



_Code quote:_
```AsciiDoc
This release is currently on StarkNet Goerli (testnets 1 and 2).
```
___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 32 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb6rKw5kJhlNatCNhB:-NIb6rKw5kJhlNatCNhC:busqeaf) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L32)):*
> ```AsciiDoc
> == StarkNet v0.10.2 (Nov 29, 22)
> 
> - This version introduces sequencer parallelization! This is the first step in our roadmap of performance upgrades. Details about the specific mechanism of parallelization and the roadmap in general will be released in a post next week.
> ```

We can now link to the post https://medium.com/starkware/starknet-performance-roadmap-bb7aae14c7de



_Code quote:_
```AsciiDoc
Details about the specific mechanism of parallelization and the roadmap in general will be released in a post next week
```
___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 35 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb8JJN8bJZcPZw-xTu:-NIb8JJN8bJZcPZw-xTv:b-wbub4v) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L35)):*
> ```AsciiDoc
> - A new endpoint, `estimate_fee_bulk`, is added to the feeder gateway. This will allow estimating the fee of several transactions at once, where each transaction is executed relative to the resulting state from applying the previous one.
> 
> Summary
> ```

I suggest changing this title to "Technical release notes", and doing so in the other versions as well (add title for the github changelog)
___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 60 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb94qv6tIjlNJcRYsV:-NIb94qv6tIjlNJcRYsW:b-jvnrsd) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L60)):*
> ```AsciiDoc
> 
> [id="version0.10.0"]
> == StarkNet v0.10.0 (Sept 05, 22)
> ```

Add quick summary before the technical release notes:
This version introduces the next step in StarkNet's account abstraction design, specifically the validate/execute separation. For more information, see https://www.notion.so/starkware/StarkNet-0-10-0-4ac978234c384a30a195ce4070461257.
___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 144 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb8XSWEOAZGWqIkm1_:-NIb8XSWEOAZGWqIkm1a:b-pp21k2) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L144)):*
> ```AsciiDoc
> [id="version0.9.0"]
> == StarkNet v0.9.0 (June 06, 22)
> ```

before the technical release notes, you can have a quick summary:

This version introduces the contract class/instance paradigm into StarkNet. For more information, see https://docs.starknet.io/documentation/architecture_and_concepts/Contracts/contract-classes/

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/136)* status: all files reviewed, 5 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 13 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb5rPeCuA69GcRS05t:-NIbB_q35CZ8YtreZT4f:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L13)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Replace with: This is the currently deployed version on StarkNet Testnets. The Mainnet environment upgrade is planned for December 12.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 32 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb6rKw5kJhlNatCNhB:-NIbBwxm8kYhwdAI4AYo:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L32)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

We can now link to the post https://medium.com/starkware/starknet-performance-roadmap-bb7aae14c7de
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 35 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb8JJN8bJZcPZw-xTu:-NIbC4j3AB9Nvxm0qsIY:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L35)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I suggest changing this title to "Technical release notes", and doing so in the other versions as well (add title for the github changelog)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 60 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb94qv6tIjlNJcRYsV:-NIbCAhdEAm9zp6XYr5f:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L60)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Add quick summary before the technical release notes:
This version introduces the next step in StarkNet's account abstraction design, specifically the validate/execute separation. For more information, see https://www.notion.so/starkware/StarkNet-0-10-0-4ac978234c384a30a195ce4070461257.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 144 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb8XSWEOAZGWqIkm1_:-NIbCRHq-_Vq4s5KHwmv:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L144)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

before the technical release notes, you can have a quick summary:

This version introduces the contract class/instance paradigm into StarkNet. For more information, see https://docs.starknet.io/documentation/architecture_and_concepts/Contracts/contract-classes/
</blockquote></details>

Done.

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/136)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 35 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb8JJN8bJZcPZw-xTu:-NIbH8Iz6h7wdEUgQ1Dc:b-iitpv2) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L35)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you make it bold/underline, I want to emphasize that both the StarkNet/Cairo section below are part of it
___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 144 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb8XSWEOAZGWqIkm1_:-NIbHSQp7ZOL4HpUVpm5:b-vr4ozp) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L144)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it?

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/136)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 35 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb8JJN8bJZcPZw-xTu:-NIbSHf-88z5qs-iz4Ig:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L35)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Can you make it bold/underline, I want to emphasize that both the StarkNet/Cairo section below are part of it
</blockquote></details>

Done.

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/136)* status: all files reviewed, 1 unresolved discussion (waiting on @JameStark)

___
*[`components/StarkNet/modules/useful_info/pages/release_versions.adoc` line 144 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-NIb8XSWEOAZGWqIkm1_:-NIbg-O548mfGdkxP5w_:bhqat54) ([raw file](https://github.com/starknet-io/starknet-docs/blob/453a1c83971655028263541f11e1e3a4e74b6c69/components/StarkNet/modules/useful_info/pages/release_versions.adoc#L144)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

> This version introduces the contract class/instance paradigm into StarkNet. For more information, see https://docs.starknet.io/documentation/architecture_and_concepts/Contracts/contract-classes/

Does this belong on 0.9.0 or 0.9.1?
</blockquote></details>

0.9.0

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/136#-:-NIbgUBG6BDkXJhJ1bpV:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @JameStark)

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Pull request merged**
