### PR TITLE
docs: Add `on_receive` function interface and note about backward compatibility

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

Added `on_receive` function and note about backward compatibility.

### PR Preview URL

[Automated actions with bridging](https://starknet-io.github.io/starknet-docs/pr-933/documentation/tools/starkgate-automated_actions_with_bridging/)
[on_receive](https://starknet-io.github.io/starknet-docs/pr-933/documentation/tools/starkgate_function_reference/#on_receive)

### Check List

- [x] Changes have been done against dev branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/933)

### CODE REVIEW

**Review by remollemo — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/933)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @stoobie)

___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 1163 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-Njdd6jd9gRRLTIFwGey:-Njdd6jd9gRRLTIFwGez:b-nyisky) ([raw file](https://github.com/starknet-io/starknet-docs/blob/892de0d160e7bb785e2be5f2aa1e3da41a6490aa/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L1163)):*
> ```AsciiDoc
> ==== Description
> 
> An interface to an implementation of the `on_receive` function that you provide in your L2 contract. When calling the `DepositWithMessage` function, the resulting transaction triggers an `on_receive` function that you need to implement in your application.
> ```

I think it's a bit unclear, and somewhat missing,
i'd make it a bit more like this:
```
Upon completion, `DepositWithMessage` function triggers a call 
to the `on_receive` callback on the receiving l2 contract.
The `on_receive` gets the deposit message as input, 
and it must return `true` for the deposit to succeed.

If the on_receive returns `false`, 
or if the receiving contract doesn’t implement `on_receive` -
The `DepositWithMessage` l1_handler
(the starknet phase of processing) will fail, 
and funds will have to be recovered using deposit cancellation.

```



_Code quote:_
```AsciiDoc
An interface to an implementation of the `on_receive` function that you provide in your L2 contract. When calling the `DepositWithMessage` function, the resulting transaction triggers an `on_receive` function that you need to implement in your application.
```
___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 1179 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-NjdbSenC6sP2ifKpKzG:-NjdbSenC6sP2ifKpKzH:bt1szpu) ([raw file](https://github.com/starknet-io/starknet-docs/blob/892de0d160e7bb785e2be5f2aa1e3da41a6490aa/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L1179)):*
> ```AsciiDoc
> [horizontal,labelwidth="25",role=stripes-odd]
> `true`:: The recipient L2 contract of the `DepositWithMessage` function accepts the funds on L2.
> `false`::  The recipient L2 contract of the `DepositWithMessage` function does not accept the funds on L2, or the `on_receive` function is not implemented in the recipients's smart contract.
> ```

1. `DepositWithMessage`  is not expected to exist on the receiving contract. actually, not the bridge as well, it exist on the L1 bridge (where the flow initiated). 
2. `on_receive` is the ep expected to exist on the receiving contract.
3. in case it doesn't exist - there will not be any returned value, as the call fail to execute altogether.



_Suggestion:_
```AsciiDoc
[horizontal,labelwidth="25",role=stripes-odd]
`true`:: The recipient L2 contract of the `DepositWithMessage` function accepts the funds on L2.
`false`::  The recipient L2 contract of the `DepositWithMessage` function does not accept the funds on L2.
```

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/933)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @remollemo)

___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 1163 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-Njdd6jd9gRRLTIFwGey:-Njs5v6j2poNvBPVT7DZ:bsyekz8) ([raw file](https://github.com/starknet-io/starknet-docs/blob/892de0d160e7bb785e2be5f2aa1e3da41a6490aa/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L1163)):*
<details><summary><i>Previously, remollemo wrote…</i></summary><blockquote>

I think it's a bit unclear, and somewhat missing,
i'd make it a bit more like this:
```
Upon completion, `DepositWithMessage` function triggers a call 
to the `on_receive` callback on the receiving l2 contract.
The `on_receive` gets the deposit message as input, 
and it must return `true` for the deposit to succeed.

If the on_receive returns `false`, 
or if the receiving contract doesn’t implement `on_receive` -
The `DepositWithMessage` l1_handler
(the starknet phase of processing) will fail, 
and funds will have to be recovered using deposit cancellation.

```
</blockquote></details>

OK, that part's clear, but as Roee explained to me, what we document here is an interface, not the actual implementation of the function. As I understand it, the information that we provide here essentially states the requirements for the implementation on the recipient contract.

Do I understand correctly?
___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 1179 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-NjdbSenC6sP2ifKpKzG:-NjsCxL1--yCCOFl4BwB:b-qsvnoa) ([raw file](https://github.com/starknet-io/starknet-docs/blob/892de0d160e7bb785e2be5f2aa1e3da41a6490aa/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L1179)):*
<details><summary><i>Previously, remollemo wrote…</i></summary><blockquote>

1. `DepositWithMessage`  is not expected to exist on the receiving contract. actually, not the bridge as well, it exist on the L1 bridge (where the flow initiated). 
2. `on_receive` is the ep expected to exist on the receiving contract.
3. in case it doesn't exist - there will not be any returned value, as the call fail to execute altogether.
</blockquote></details>

Done. PTAL.

**Review by remollemo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/933)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @stoobie)

___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 1163 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-Njdd6jd9gRRLTIFwGey:-Njt-NKj8w-Wgb_loeth:b-ljaz40) ([raw file](https://github.com/starknet-io/starknet-docs/blob/892de0d160e7bb785e2be5f2aa1e3da41a6490aa/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L1163)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

OK, that part's clear, but as Roee explained to me, what we document here is an interface, not the actual implementation of the function. As I understand it, the information that we provide here essentially states the requirements for the implementation on the recipient contract.

Do I understand correctly?
</blockquote></details>

the verbiage i gave has nothing to do with the implementation , but with the expected behaviour.
The interface is not a list of selectors, but a collection of functions and events with an expected behaviour.
it's important to explain what is is the required behaviour of the interface is, or the bound parties would break.

**Review by remollemo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/933)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @stoobie)

___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 1206 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-Njt0_uF9VDwRJA9zqbF:-Njt0_uF9VDwRJA9zqbG:b-rwii2e) ([raw file](https://github.com/starknet-io/starknet-docs/blob/3e3bfe3753a0ccdcfee1aa32389667ccbc6ff528/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L1206)):*
> ```AsciiDoc
> 
> If `on_receive` returns `false`, or if the receiving contract does not implement `on_receive`,
> The `depositWithMessage` L1 handler fails, and the user must recover their funds using the xref:#depositWithMessageCancelRequest[`depositWithMessageCancelRequest`] function.
> ```

it's not that the user MUST recover etc., they simply have no other way to recover the funds. i.e. they are stuck in the belly of the L1 contract, and only using deposit cancel it can be recovered.



_Code quote:_
```AsciiDoc
If `on_receive` returns `false`, or if the receiving contract does not implement `on_receive`,
The `depositWithMessage` L1 handler fails, and the user must recover their funds using the xref:#depositWithMessageCancelRequest[`depositWithMessageCancelRequest`] function.
```

**Review by remollemo — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/933)* status: all files reviewed, 2 unresolved discussions (waiting on @stoobie)

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/933)* status: all files reviewed, 2 unresolved discussions (waiting on @remollemo)

___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 1163 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-Njdd6jd9gRRLTIFwGey:-NjvDQrVA6hWJiIPFGtP:bwj8mbi) ([raw file](https://github.com/starknet-io/starknet-docs/blob/892de0d160e7bb785e2be5f2aa1e3da41a6490aa/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L1163)):*
<details><summary><i>Previously, remollemo wrote…</i></summary><blockquote>

the verbiage i gave has nothing to do with the implementation , but with the expected behaviour.
The interface is not a list of selectors, but a collection of functions and events with an expected behaviour.
it's important to explain what is is the required behaviour of the interface is, or the bound parties would break.
</blockquote></details>

Agreed that I need to describe the expected behavior. In addition to this function, the  `depositWithMessage` section also describes this behavior. I think it also should have a dedicated topic just 
explaining the functionality of depositWithMessage and I'll explain the flow there.

So after I explain the flow, and why you need to implement `on_receive` in the L2 recipient contract, I need to explain in this particular section the `on_receive` that we provide in https://github.com/starkware-libs/starkgate/blob/9ce762a8eb187984438669b03917a64de5a23de5/src/cairo/receiver\_interface.cairo#L6.

So how would you describe what we provide? Is it an interface? Is it an example of the bare minimum that a recipient contract needs to implement? Is it something else?

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/933)* status: all files reviewed, 2 unresolved discussions (waiting on @remollemo)

___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 1206 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-Njt0_uF9VDwRJA9zqbF:-NjvF4DI5UBCufzWKpRP:bme4ojt) ([raw file](https://github.com/starknet-io/starknet-docs/blob/3e3bfe3753a0ccdcfee1aa32389667ccbc6ff528/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L1206)):*
OK. I changed it to:

>  the user can only recover their funds using the `depositWithMessageCancelRequest` function.

**Review by remollemo — COMMENTED** [review]
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/933)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @stoobie)

___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 1224 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-NkAJKF21EG0toTXYXiB:-NkAJKF36ugk_U6NO_U4:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/99f97fca1a6261e50e31498924f23082391762e3/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L1224)):*
> ```AsciiDoc
> `true`:: The recipient L2 contract of the `depositWithMessage` function accepts the funds on L2.
> `false`:: The recipient L2 contract of the `depositWithMessage` function does not accept the funds on L2.
> No value:: If the recipients's smart contractdoes not implement the `on_receive` function, the call fails to execute and no value is returned.
> ```





_Suggestion:_
```AsciiDoc
 contract does
```
___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 1224 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-NkAJOVC2-Wrqqlty-IW:-NkAJOVC2-Wrqqlty-IX:b-mr2xhr) ([raw file](https://github.com/starknet-io/starknet-docs/blob/99f97fca1a6261e50e31498924f23082391762e3/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L1224)):*
> ```AsciiDoc
> `true`:: The recipient L2 contract of the `depositWithMessage` function accepts the funds on L2.
> `false`:: The recipient L2 contract of the `depositWithMessage` function does not accept the funds on L2.
> No value:: If the recipients's smart contractdoes not implement the `on_receive` function, the call fails to execute and no value is returned.
> ```

No return value implies successful execution. this is not the case here. if the on_receive is not implemented  onthe callee, the call will fail to execute.



_Code quote:_
```AsciiDoc
No value:: If the recipients's smart contractdoes not implement the `on_receive` function, the call fails to execute and no value is returned.
```

**Review by remollemo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/933)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @stoobie)

___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 300 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-NkAUHsz804_fA1xBKvd:-NkAUHsz804_fA1xBKve:b-qjmow8) ([raw file](https://github.com/starknet-io/starknet-docs/blob/99f97fca1a6261e50e31498924f23082391762e3/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L300)):*
> ```AsciiDoc
> After depositing to another recipient, the L1 handler in `token_bridge.cairo` calls the `on_receive` function in the contract of the recipient.
> 
> If `on_receive` returns `true`, then the operation succeeded. If it returns `false`, or if it doesn't return any value because the `on_receive` function is not implemented in the recipient contract, the transaction is reverted.
> ```

The operation can fail regardless of `on _receive`. If on_reveive didn't return with true - the opeation surely fails, as "on_receive must return true to succeed". the opposite doesnt apply...



_Code quote:_
```AsciiDoc
If `on_receive` returns `true`, then the operation succeeded. If it returns `false`, or if it doesn't return any value because the `on_receive` function is not implemented in the recipient contract, the transaction is reverted.
```

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/933)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @remollemo)

___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 300 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-NkAUHsz804_fA1xBKvd:-NkTnRVx50p7b_RjJl85:bzh73jb) ([raw file](https://github.com/starknet-io/starknet-docs/blob/99f97fca1a6261e50e31498924f23082391762e3/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L300)):*
<details><summary><i>Previously, remollemo wrote…</i></summary><blockquote>

The operation can fail regardless of `on _receive`. If on_reveive didn't return with true - the opeation surely fails, as "on_receive must return true to succeed". the opposite doesnt apply...
</blockquote></details>

Fixed. PTAL. If it's still not correct, please add a suggestion for what it should say.
___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 1224 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-NkAJOVC2-Wrqqlty-IW:-NkTnhPtCNchRie9FCPP:b-73um02) ([raw file](https://github.com/starknet-io/starknet-docs/blob/99f97fca1a6261e50e31498924f23082391762e3/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L1224)):*
<details><summary><i>Previously, remollemo wrote…</i></summary><blockquote>

No return value implies successful execution. this is not the case here. if the on_receive is not implemented  onthe callee, the call will fail to execute.
</blockquote></details>

Fixed. PTAL.
___
*[`components/Starknet/modules/tools/pages/starkgate_function_reference.adoc` line 1224 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/933#-NkAJKF21EG0toTXYXiB:-NkTo73a3ZhKH18P5A_O:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/99f97fca1a6261e50e31498924f23082391762e3/components/Starknet/modules/tools/pages/starkgate_function_reference.adoc#L1224)):*
> ```AsciiDoc
> `true`:: The recipient L2 contract of the `depositWithMessage` function accepts the funds on L2.
> `false`:: The recipient L2 contract of the `depositWithMessage` function does not accept the funds on L2.
> No value:: If the recipients's smart contractdoes not implement the `on_receive` function, the call fails to execute and no value is returned.
> ```

Done.

**Pull request merged**
