### PR TITLE
docs: Updates to Messaging mechanism

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

Updates implemented in PR #857, minus questions/comments that are still unanswered or TBD.

### PR Preview URL

[L1-L2 Messaging mechanism](https://starknet-io.github.io/starknet-docs/pr-1244/documentation/architecture_and_concepts/Network_Architecture/messaging-mechanism)

### Check List

- [x] Changes have been done against main branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1244)

### CODE REVIEW

**Comment by avi-starkware** [comment]
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 23 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHLPGBAKiiYKPKwn0O:-NxHLPGBAKiiYKPKwn0P:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L23)):*
> ```AsciiDoc
> 
> . During the execution of a transaction, a contract on Starknet sends a message from L2 to L1 by calling the `send_message_to_L1` syscall.
> . The sequencer attaches the message parameters to the state update that includes the syscall invocation. The message parameters include the address of the recipient contract on L1 and the message data.
> ```





_Suggestion:_
```AsciiDoc
. The sequencer attaches the message parameters to the state update that includes the syscall invocation. The message parameters include the address of the sender on L2, the address of the recipient contract on L1, and the message data.
```

**Comment by avi-starkware** [comment]
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 23 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHLPGBAKiiYKPKwn0O:-NxHLyFV3_zWftB6EHmh:bufy62p) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L23)):*
> ```AsciiDoc
> 
> . During the execution of a transaction, a contract on Starknet sends a message from L2 to L1 by calling the `send_message_to_L1` syscall.
> . The sequencer attaches the message parameters to the state update that includes the syscall invocation. The message parameters include the address of the recipient contract on L1 and the message data.
> ```

Oh wait, do you mean the parameters of the `send_message_to_l1_syscall`(as in the example below), or the parameters of the message itself as it appears in the block? From the first sentence of this bullet, it seems you mean the block / state update and it does include the sender address as well.

**Comment by avi-starkware** [comment]
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 23 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHLPGBAKiiYKPKwn0O:-NxHNVSm0EiKPCaItXjD:b-9ghk0) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L23)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Oh wait, do you mean the parameters of the `send_message_to_l1_syscall`(as in the example below), or the parameters of the message itself as it appears in the block? From the first sentence of this bullet, it seems you mean the block / state update and it does include the sender address as well.
</blockquote></details>

I'm am not sure about your terminology, but to be more exact, only the block contains the L2 -> L1 messages. The state update only contains the root, storage diffs, nonces, and deployed classes. [Here's](https://alpha-mainnet.starknet.io/feeder_gateway/get_state_update?blockHash=0xb2bb557e370ac3dbc5bb41e76c4ce0a02a3afe45a4bc4d9e603fb7645df08d) an example for a state update that has messages, and [this](https://alpha-mainnet.starknet.io/feeder_gateway/get_block?blockHash=0xb2bb557e370ac3dbc5bb41e76c4ce0a02a3afe45a4bc4d9e603fb7645df08d) is the corresponding block. You can see the messages appear in the json of the block in this example, but not in the corresponding state update.
(Use a chrome extension such as JSON Formatting, to see the json in a readable format in the browser.)

**Comment by avi-starkware** [comment]
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 54 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHP2mGBQH6QvVb8YBb:-NxHP2mGBQH6QvVb8YBc:b-z0qpzu) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L54)):*
> ```AsciiDoc
> [#diagram_l2-l1_messaging_mechanism]
> .L2->L1 Messaging mechanism
> image::l2l1.png[L2->L1 message mechanism]
> ```

Should the numbers in red circles refer to the items above? I think they are mismatched.



_Code quote:_
```AsciiDoc
xref:#diagram_l2-l1_messaging_mechanism[] illustrates this flow:

[#diagram_l2-l1_messaging_mechanism]
.L2->L1 Messaging mechanism
image::l2l1.png[L2->L1 message mechanism]
```

**Comment by avi-starkware** [comment]
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 63 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHPkJz3Neck2Z8Kucx:-NxHPkJz3Neck2Z8Kucy:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L63)):*
> ```AsciiDoc
> 
> [horizontal,labelwidth="30",role="stripes-odd"]
> from_address (`felt252`):: The address of the L2 contract sending the message.
> ```





_Suggestion:_
```AsciiDoc
`from_address` (`felt252`):: The address of the L2 contract sending the message.
```

**Comment by avi-starkware** [comment]
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 105 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHopMU-fg8V9mpAElU:-NxHopMU-fg8V9mpAElV:bcgxyfk) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L105)):*
> ```AsciiDoc
> . The L1 Handler transaction that was created in the previous step is added to a proof.
> . The Core Contract receives the state update.
> . The message is cleared from the Core Contract's storage. At this point, the message is handled.
> ```

This step also incurs a fee that is similar to the fee charged for L2 -> L1 messages (this is mentioned for L2 -> L1 messages in the NOTE above):
* 5000 gas for clearing the L1 storage to consume the message (instead of the 20000 charged for L2 -> L1 messages).
* This also emits an L1 event logging this consumption.

I think these costs are not actually being charged, though...
@ArielElp, what exactly happens when charging L1 handler fees?



_Code quote:_
```AsciiDoc
. The message is cleared from the Core Contract's storage. At this point, the message is handled.
```

**Comment by avi-starkware** [comment]
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 23 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHLPGBAKiiYKPKwn0O:-NxLpwxhDi944nODa6cm:bp93aqd) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L23)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I'm am not sure about your terminology, but to be more exact, only the block contains the L2 -> L1 messages. The state update only contains the root, storage diffs, nonces, and deployed classes. [Here's](https://alpha-mainnet.starknet.io/feeder_gateway/get_state_update?blockHash=0xb2bb557e370ac3dbc5bb41e76c4ce0a02a3afe45a4bc4d9e603fb7645df08d) an example for a state update that has messages, and [this](https://alpha-mainnet.starknet.io/feeder_gateway/get_block?blockHash=0xb2bb557e370ac3dbc5bb41e76c4ce0a02a3afe45a4bc4d9e603fb7645df08d) is the corresponding block. You can see the messages appear in the json of the block in this example, but not in the corresponding state update.
(Use a chrome extension such as JSON Formatting, to see the json in a readable format in the browser.)
</blockquote></details>

Sorry, [this](https://alpha-mainnet.starknet.io/feeder_gateway/get_block?blockHash=0x00b2bb557e370ac3dbc5bb41e76c4ce0a02a3afe45a4bc4d9e603fb7645df08d) is the block I meant to refer you to, and [this](https://alpha-mainnet.starknet.io/feeder_gateway/get_state_update?blockHash=0x00b2bb557e370ac3dbc5bb41e76c4ce0a02a3afe45a4bc4d9e603fb7645df08d) is the corresponding state update.

Look at transaction `0xecd259e52ef5061081559c80c0b5f1560caaca7f198a6bf90a74d866593b1` to find a non-empty message.

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1244)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp and @stoobie)

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1244)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp and @avi-starkware)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 54 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHP2mGBQH6QvVb8YBb:-NxHwgKO-_F1pig0Kv7w:bx8qm2u) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L54)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Should the numbers in red circles refer to the items above? I think they are mismatched.
</blockquote></details>

Yeah, I have to update the diagram. I'm going to do that in a separate PR.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 63 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHPkJz3Neck2Z8Kucx:-NxHynog2ykmSqdFLPau:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L63)):*
> ```AsciiDoc
> 
> [horizontal,labelwidth="30",role="stripes-odd"]
> from_address (`felt252`):: The address of the L2 contract sending the message.
> ```

Done.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 105 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHopMU-fg8V9mpAElU:-NyEvL3531eU_XGOb4aU:b-cyfoz7) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L105)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This step also incurs a fee that is similar to the fee charged for L2 -> L1 messages (this is mentioned for L2 -> L1 messages in the NOTE above):
* 5000 gas for clearing the L1 storage to consume the message (instead of the 20000 charged for L2 -> L1 messages).
* This also emits an L1 event logging this consumption.

I think these costs are not actually being charged, though...
@ArielElp, what exactly happens when charging L1 handler fees?
</blockquote></details>

@avi-starkware Is this not covered already in https://starknet-io.github.io/starknet-docs/pr-1244/documentation/architecture_and_concepts/Network_Architecture/messaging-mechanism/#l1_l2_message_structure?

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1244)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 105 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHopMU-fg8V9mpAElU:-NyExggq6cnRQTdUOkzj:b-lx9chx) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L105)):*
I don't see it there. All it says is
> The fee itself is calculated in the [same manner](https://starknet-io.github.io/starknet-docs/pr-1244/documentation/architecture_and_concepts/Network_Architecture/fee-mechanism/#overall_fee) as "regular" L2 transactions. You can use the [CLI](https://starknet-io.github.io/starknet-docs/pr-1244/documentation/cli/starkli/#starknet-estimate_fee) to get an estimate of an L1 → L2 message fee.

But as I said above, I know that additional L1 costs are added to the calculation, and it's not just the normal fee calculation for "regular" transactions.

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1244)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @avi-starkware)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 23 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHLPGBAKiiYKPKwn0O:-Nzgsn3V3QFH1cK9sFBM:b-pi2wfw) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L23)):*
@avi-starkware  So is this correct:
> The sequencer attaches the message parameters to the block that includes the syscall invocation.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc` line 105 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-NxHopMU-fg8V9mpAElU:-NzhCmRk2vb0gsZdl3ej:bhux6am) ([raw file](https://github.com/starknet-io/starknet-docs/blob/297609cd9c893c4dedff210cdc5130877ec1f4ba/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc#L105)):*
@avi-starkware I changed this line as follows:

> . The message is cleared from the Core Contract's storage to consume the message. Clearing the Core Contract's storage does the following:  
  
> * incurs a fixed cost of 5,000 gas  
> * emits an L1 event logging the message consumption

I'm checking on whether we actually charge the fee.

**Review by avi-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1244#-:-NzhgQFIEeB8J64y56rD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
