### PR TITLE
fix: removed image from L1-L2 communication

### PR DESCRIPTION
**Pull request by LandauRaz**
### Description of the Changes

Removed image from L1-L2 communication, approved by Shani.

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-698/documentation/architecture_and_concepts/L1-L2_Communication/messaging-mechanism/

### Check List

- [x] Changes have been done against dev branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/698)

### CODE REVIEW

**Review by stoobie — CHANGES_REQUESTED** [review]
@LandauRaz Please state in the description who gave technical approval for this change.

**Review by JameStark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/698#-:-NagCOGP8zGUQYsHUJDR:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by LandauRaz** [comment]
@stoobie, can please you unblock?

**Review by stoobie — APPROVED** [review]
LGTM

**Pull request merged**
