### PR TITLE
v0.11.0: Add updated transaction page

### PR DESCRIPTION
**Pull request by JameStark**
### Description of the Changes

Add updated transaction page for v0.11.0

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-281/documentation/

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/281)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/281)* status: all files reviewed, 2 unresolved discussions (waiting on @bbrandtom and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 73 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/281#-NOjcTrN-jAdrhxQCE-K:-NOjcTrN-jAdrhxQCE-L:b-i9nkuo) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b22e3bc7dbdefe21646eb75795d17dbc90a07b7c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L73)):*
> ```AsciiDoc
> |===
> 
> === Invoke transaction version 0
> ```

I'm not sure about deleting this, since old v0 transactions still exist (you just can't send new ones), people might still look here to see e.g. how is the hash computed. I'm wondering about just keeping this section here for now, WDYT? 
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 184 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/281#-NOjc1Wj8d-GXbtxIgJ5:-NOjc1Wk2CTum-dO0USW:btjn5dh) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b22e3bc7dbdefe21646eb75795d17dbc90a07b7c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L184)):*
> ```AsciiDoc
> * stem:[$h$] is the xref:../Hashing/hash-functions.adoc#pedersen-hash[Pedersen] hash
> 
> ## Deploy account transaction
> ```

Why is this removed? (didn't we just add it?)

I would add a todo for the deploy_account tx hash

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/281)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 184 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/281#-NOjc1Wj8d-GXbtxIgJ5:-NOnFUVI9QisVAk7BPwu:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b22e3bc7dbdefe21646eb75795d17dbc90a07b7c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L184)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Why is this removed? (didn't we just add it?)

I would add a todo for the deploy_account tx hash
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/281)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 73 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/281#-NOjcTrN-jAdrhxQCE-K:-NOnIh289648EwUusPo9:bd6644l) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b22e3bc7dbdefe21646eb75795d17dbc90a07b7c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L73)):*
> eople might still lo
Ah ok, I thought it was going to be fully removed with regenesis. Makes sense to keep it in there then and add a note explaining its only for existing v0 txns

**Review by JameStark — COMMENTED** [review]
> Reviewed 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/281)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp and @bbrandtom)

**Pull request closed without merging**
