### PR TITLE
(Obsolete) docs: system calls; PR#63 replaces this PR

### PR DESCRIPTION
**Pull request by ArielElp**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] Docs have been updated
- [ ] PR title is follow the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/38)

### CODE REVIEW

**Review by stoobie — COMMENTED** [review]
One comment for now.

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/38)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @bbrandtom and @stoobie)

___
*[`docs/Contracts/system-calls.md` line 11 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/38#-N3Xs5msA_B8mtEPj8GS-r1-11:-N9UuV556TMMgZb5QeiV:bonekid) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a810c53ff927f8cce44b0d90d64a69c780736b02/docs/Contracts/system-calls.md#L11)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

```suggestion
Send a message from the StarkNet OS to L1. 

This includes the message parameters as part of the proof's output, exposing them to the StarkNet Core contract on L1 once the state update, including the transaction, is received. For more information, see StarkNet's [messaging mechanism](../L1-L2%20Communication/messaging-mechanism).
```
</blockquote></details>

changed the second sentence, didn't like the first one.
The OS is helping ME do stuff. I'm (i.e. the contract) doing the sending.

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/38)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`docs/Contracts/system-calls.md` line 55 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/38#-N3Y4IMi6_FLIQ3O71R_:-N3Y4IMi6_FLIQ3O71Ra:b-19iwme) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a810c53ff927f8cce44b0d90d64a69c780736b02/docs/Contracts/system-calls.md#L55)):*
> ```Markdown
> Deploys a new instance of a previously declared class.
> 
> This system call expects the class hash of the contract to be deployed, salt (used in the computation of the [contract's address](./contract-address), and constructor arguments. The deploy syscall can be raised by calling the following function, which is available in `syscalls.cairo`:
> ```

this was confusing to me.
It sounds like the syscall expects the class hash that is given to it to be already deployed.
I suggest listing it somehow in bullets



_Code quote:_
```Markdown
class hash of the contract to be deployed
```
___
*[`docs/Contracts/system-calls.md` line 8 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/38#-NA-Dhad1FXbF0Njd_-_:-NA-Dhad1FXbF0Njd_-a:b5zxszn) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/01842bf00af83310aec5172a2a6b1bf78af276c5/docs/Contracts/system-calls.md#L8)):*
> ```Markdown
> 
> ## Supported System Calls
> ```

What is the order of the system calls?
___
*[`docs/Contracts/system-calls.md` line 51 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/38#-N9jctx9CGXzNp7ItMeS:-N9jcrYS3RkLu93PlGV2:bs2z9e7) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/01842bf00af83310aec5172a2a6b1bf78af276c5/docs/Contracts/system-calls.md#L51)):*
> ```Markdown
> ```
> 
> ### Deploy
> ```

Missing - 
1. a link to the syscall
2. does it return the address?

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/38)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @Adi-Yakovian, @ArielElp, and @bbrandtom)

___
*[`docs/Contracts/system-calls.md` line 11 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/38#-N3Xs5msA_B8mtEPj8GS-r1-11:-NAF9GPf1wUbrROmWvbK:bm1x7vp) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a810c53ff927f8cce44b0d90d64a69c780736b02/docs/Contracts/system-calls.md#L11)):*
> Send a message from the StarkNet OS to L1. 
> 
> This includes the message parameters as part of the proof's output, exposing them to the StarkNet Core contract on L1 once the state update, including the transaction, is received. For more information, see StarkNet's [messaging mechanism](../L1-L2%20Communication/messaging-mechanism).
OK..."Requests the StarkNet OS" doesn't sound right. "Sends a request to the StarkNet OS" or "Asks the StarkNet OS" or "Tells the StarkNet OS"..."Requests the StarkNet OS" sounds like you're asking someone to give you the StarkNet OS.
___
*[`docs/Contracts/system-calls.md` line 5 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/38#-NAF5fm46lhITepbCD3C:-NAF5fm46lhITepbCD3D:b-gpdwd4) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a11523ef2f228e0b4ec04be34f67e6819d701ded/docs/Contracts/system-calls.md#L5)):*
> ```Markdown
> ## Introduction
> 
> StarkNet smart contracts are written in Cairo. However, Cairo is (among other things, see the [whitepaper](https://eprint.iacr.org/2021/1063.pdf) for more details) a general purpose language, not necessarily aimed at writing contract language. Thus, some additional capabilities are needed for operations that make sense in a smart contract context but not in a standalone program, e.g. calling another contract or accessing the contract's storage. To this end, we introduce system calls to our smart contract language. System calls are a way for the contract to require services from the StarkNet OS. Using these services, a function inside the contract can obtain information that would otherwise be inaccessible, as it depends on the broader state of StarkNet rather than local variables that appear in the function's scope.
> ```

StarkNet smart contracts are written in Cairo. However, Cairo is a general purpose language, not necessarily aimed at writing contract language. Cairo is, in fact much more. For details, see [Cairo – a Turing-complete STARK-friendly CPU architecture](https://eprint.iacr.org/2021/1063.pdf).



_Code quote:_
```Markdown
StarkNet smart contracts are written in Cairo. However, Cairo is (among other things, see the [whitepaper](https://eprint.iacr.org/2021/1063.pdf) for more details) a general purpose language, not necessarily aimed at writing contract language.
```
___
*[`docs/Contracts/system-calls.md` line 5 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/38#-NAF6OPl-wVLSHZjCkQl:-NAF6OPl-wVLSHZjCkQm:b8aafpe) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a11523ef2f228e0b4ec04be34f67e6819d701ded/docs/Contracts/system-calls.md#L5)):*
> ```Markdown
> ## Introduction
> 
> StarkNet smart contracts are written in Cairo. However, Cairo is (among other things, see the [whitepaper](https://eprint.iacr.org/2021/1063.pdf) for more details) a general purpose language, not necessarily aimed at writing contract language. Thus, some additional capabilities are needed for operations that make sense in a smart contract context but not in a standalone program, e.g. calling another contract or accessing the contract's storage. To this end, we introduce system calls to our smart contract language. System calls are a way for the contract to require services from the StarkNet OS. Using these services, a function inside the contract can obtain information that would otherwise be inaccessible, as it depends on the broader state of StarkNet rather than local variables that appear in the function's scope.
> ```

So writing smart contracts requires some operations, such as such as calling another contract or accessing the contract's storage, that standalone programs do not require.

The StarkNet contract language supports these operations by using system calls. System calls enable a contract to require services from the StarkNet OS. You can use system calls in a function to get information that depends on the broader state of StarkNet, which would otherwise be inaccessible, rather than local variables that appear in the function's scope.



_Code quote:_
```Markdown
Thus, some additional capabilities are needed for operations that make sense in a smart contract context but not in a standalone program, e.g. calling another contract or accessing the contract's storage. To this end, we introduce system calls to our smart contract language. System calls are a way for the contract to require services from the StarkNet OS. Using these services, a function inside the contract can obtain information that would otherwise be inaccessible, as it depends on the broader state of StarkNet rather than local variables that appear in the function's scope.
```

**Pull request closed without merging**
