### PR TITLE
Docs: Add Quillaudits to Audit providers

### PR DESCRIPTION
**Pull request by devwankel**
### Description of the Changes

This PR Adds Quillaudits to Audit providers.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [x] Changes have been done against master branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1040)

### CODE REVIEW

**Comment by odednaor** [comment]
@devwankel I've sent an email to `hello@quillhash.com`.

**Comment by devwankel** [comment]
@odednaor I'm not from the Quillaudits team. I saw that they provide a Starknet audits service and wanted to add it.
https://www.quillaudits.com/services/starknet-smart-contract-security-audit

**Comment by stoobie** [comment]
@devwankel 
The default branch for this repo is now `main` instead of `master`. [Please follow these steps to update your local repos to use main instead of master from now on.](https://github.com/starknet-io/starknet-docs/discussions/964#discussioncomment-7982322)

**Comment by devwankel** [comment]
Hi @stoobie I updated it.

**Comment by stoobie** [comment]
> Hi @stoobie I updated it.

Ok, thanks.

**Comment by odednaor** [comment]
Quillaudits did not respond to email asking for more details. Can close this PR.

**Comment by stoobie** [comment]
> Quillaudits did not respond to an email asking for more details. Can close this PR.

Closing

**Pull request closed without merging**
