### PR TITLE
v0.11.0 Data availability

### PR DESCRIPTION
**Pull request by JameStark**
### Description of the Changes

v0.11.0 Update onchain data

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-285/documentation/

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/285)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/285)* status: all files reviewed, 8 unresolved discussions (waiting on @bbrandtom and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 18 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp5U9z9h5KFgrDK6o7:-NOp5U9z9h5KFgrDK6o8:b-7j95xw) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L18)):*
> ```AsciiDoc
> Those differences are sent as `uint256[]` array as part of the calldata, and are encoded as follows:
> 
> * Number of contracts whose storage is updated
> ```

state



_Code quote:_
```AsciiDoc
storage
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 19 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp50NGAlePZiSiZr9k:-NOp50NGAlePZiSiZr9l:b-qjygs9) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L19)):*
> ```AsciiDoc
> 
> * Number of contracts whose storage is updated
> * `flag` (0 = Storage updates only / 1 = Deployed or replaced)
> ```

It's better now, but I think it's more clear if we do:

* For each affected contract, we have a single word encoding (see below the exact format):
* * flag...
* * nonce...
* * num of storage updates

and here the image
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 33 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp7vX-EiXMpKY6O-jZ:-NOp7vX-EiXMpKY6O-j_:b-foseh0) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L33)):*
> ```AsciiDoc
> *** `key` - the address inside the contract's storage where the value is updated
> *** `value` - the new value
> ```

Add the following (there is a section I didn't previously discuss, it's now in the updated upcoming version page, see changelog)

Next, we have information about newly declared classes:
* The # of (Cairo 1.0) classes that were declared in the block
* For each class we have:
* * The class hash
* * The compiled class hash (link to the intro in the upcoming version page, it explains this notion)
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 72 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp5zmd5yZwL3Vx3q62:-NOp5zmd5yZwL3Vx3q63:b-7j95xw) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L72)):*
> ```AsciiDoc
> ----
> 
> * The first element, `5` (index 6 in the array), is the number of contracts whose storage was updated. We will take only the first contract as an example.
> ```

state



_Code quote:_
```AsciiDoc
storage
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 72 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp6DF25QEzHh91cmCn:-NOp6DF32Di29dzE5GKF:b-l6mwxj) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L72)):*
> ```AsciiDoc
> ----
> 
> * The first element, `5` (index 6 in the array), is the number of contracts whose storage was updated. We will take only the first contract as an example.
> ```

remove



_Code quote:_
```AsciiDoc
(index 6 in the array)
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 78 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp6fFtC0GAFDo4Grup:-NOp6fFtC0GAFDo4Gruq:b43zedy) ([raw file](https://github.com/starknet-io/starknet-docs/blob/17c585d66a2aef7f4bfb1288deafa689d82050b8/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L78)):*
> ```AsciiDoc
> 
> * The first element, 2, is the number of cells that encode contracts deployment.
> * The next two elements describe a single contract deployment with the following parameters:
> ```

Let's keep this text, just the numbers should be different



_Code quote:_
```AsciiDoc
 The next two elements describe a single contract deployment with the following parameters:
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 85 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp6mYt-RmMTrCCVY4X:-NOp6mYt-RmMTrCCVY4Y:b-wg38dz) ([raw file](https://github.com/starknet-io/starknet-docs/blob/17c585d66a2aef7f4bfb1288deafa689d82050b8/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L85)):*
> ```AsciiDoc
> ----
> 
>  ** `contract_hash`:
> ```

The word encoding the flag / updated nonce/ # of storage updates



_Code quote:_
```AsciiDoc
`contract_hash`
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 88 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp7Fpd6U9e4YzQMprX:-NOp7Fpd6U9e4YzQMprY:b-tmbtso) ([raw file](https://github.com/starknet-io/starknet-docs/blob/17c585d66a2aef7f4bfb1288deafa689d82050b8/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L88)):*
> ```AsciiDoc
> +
> ----
> 1336043477925910602175429627555369551262229712266217887481529642650907574765
> ```

`18446744073709551617`, which is stem:[$2^{64}+1$], thus:
* flag = 0, so the contract class isn't replaced, nor was the contract just deployed, i.e. there is no need to specify the class hash
* The new contract nonce is 1
* One storage key is updated:
  ** The value at key 5 was changed to 102.

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/285)* status: all files reviewed, 8 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 18 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp5U9z9h5KFgrDK6o7:-NOsPMB20HOWPCCUHvI9:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L18)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

state
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 72 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp5zmd5yZwL3Vx3q62:-NOsPQu39zMiuqRJ9rG5:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L72)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

state
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 72 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp6DF25QEzHh91cmCn:-NOsPV2833CgV7fWZlv9:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L72)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/285)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 19 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp50NGAlePZiSiZr9k:-NOtQ3jLCDhztNV5JgQ-:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L19)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

It's better now, but I think it's more clear if we do:

* For each affected contract, we have a single word encoding (see below the exact format):
* * flag...
* * nonce...
* * num of storage updates

and here the image

</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 33 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp7vX-EiXMpKY6O-jZ:-NOtQqDhDhna5hnRGaZK:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L33)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Add the following (there is a section I didn't previously discuss, it's now in the updated upcoming version page, see changelog)

Next, we have information about newly declared classes:
* The # of (Cairo 1.0) classes that were declared in the block
* For each class we have:
* * The class hash
* * The compiled class hash (link to the intro in the upcoming version page, it explains this notion)

</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 78 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp6fFtC0GAFDo4Grup:-NOtR1Is9b67WtUENj86:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/17c585d66a2aef7f4bfb1288deafa689d82050b8/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L78)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Let's keep this text, just the numbers should be different
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 85 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp6mYt-RmMTrCCVY4X:-NOtS6SP2yXKPNVld-k2:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/17c585d66a2aef7f4bfb1288deafa689d82050b8/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L85)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

The word encoding the flag / updated nonce/ # of storage updates
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 88 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp7Fpd6U9e4YzQMprX:-NOtRk4p2X2tsbfd0Soq:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/17c585d66a2aef7f4bfb1288deafa689d82050b8/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L88)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

`18446744073709551617`, which is stem:[$2^{64}+1$], thus:
* flag = 0, so the contract class isn't replaced, nor was the contract just deployed, i.e. there is no need to specify the class hash
* The new contract nonce is 1
* One storage key is updated:
  ** The value at key 5 was changed to 102.

</blockquote></details>

Done.

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/285)* status: all files reviewed, 8 unresolved discussions (waiting on @bbrandtom and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 18 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp5U9z9h5KFgrDK6o7:-NOxEEfz4h9-GcO48bZD:b-tkffji) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L18)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

don't see change
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 19 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp50NGAlePZiSiZr9k:-NOxEHjH64zupD-WoEPl:b-ygsous) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L19)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I didn't mean ... literally :) I meant the same description you put initially.

The change I'm suggestion is having flag,nonce,number of storage updates all under the bulletpoint:

* For each affected contract, we have a single word encoding (see below the exact format):

and then it's clearer what the image is describing (IMO at least)
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 33 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp7vX-EiXMpKY6O-jZ:-NOxEkOuCseeb2KqQW6E:bxwycqx) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L33)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This isn't replacing the storage updates section, it comes after it
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 72 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp5zmd5yZwL3Vx3q62:-NOxExpDC4l423QmNeqT:b-tkffji) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L72)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

don't see change

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/285)* status: 2 of 207 files reviewed, 8 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 18 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp5U9z9h5KFgrDK6o7:-NOxSC6BBVZ0m7TYaqSH:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L18)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

don't see change
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 72 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp5zmd5yZwL3Vx3q62:-NOxSEDu2Fn15zgOULim:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L72)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

don't see change
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/285)* status: 2 of 207 files reviewed, 8 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 19 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp50NGAlePZiSiZr9k:-NOxV3tT8xnI75UhbQ84:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L19)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I didn't mean ... literally :) I meant the same description you put initially.

The change I'm suggestion is having flag,nonce,number of storage updates all under the bulletpoint:

* For each affected contract, we have a single word encoding (see below the exact format):

and then it's clearer what the image is describing (IMO at least)
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/285)* status: 2 of 207 files reviewed, 8 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 33 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp7vX-EiXMpKY6O-jZ:-NOxXsmvEFKr460InKV9:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L33)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

This isn't replacing the storage updates section, it comes after it
</blockquote></details>

Done

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/285)* status: 2 of 207 files reviewed, 11 unresolved discussions (waiting on @bbrandtom and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 72 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp6DF25QEzHh91cmCn:-NPGRUGW-Ib363U9e_Tt:bz2tcqv) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L72)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still there
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 75 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NPGR_eK6LzWHeeZ59gn:-NPGR_eK6LzWHeeZ59go:b-lr2x9g) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aa35b2c97c0efc1f55e0ce0870cb023b00a5527/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L75)):*
> ```AsciiDoc
> ----
> 
> * The first element, `5` (index 6 in the array), is the number of contracts whose storage was updated. We will take only the first contract as an example.
> ```

In the preview this is a separate point for some reason



_Code quote:_
```AsciiDoc
We will take only the first contract as an example
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 16 at r15](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NPGQmgS3_N3p_71_Sqq:-NPGQmgS3_N3p_71_Sqr:b-xyqnb4) ([raw file](https://github.com/starknet-io/starknet-docs/blob/08480fec0be4bc1673f388188ee6dc59ecf68dcb/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L16)):*
> ```AsciiDoc
> The state diffs contain information on every contract whose storage was updated and additional information on contract deployments.
> 
> For each affected contract, we have a single word encoding (see below the exact format):
> ```

that encodes (reading this now feels weird, as if we're saying "word-encoding" and the sentence abruptly ends)



_Code quote:_
```AsciiDoc
encoding
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 18 at r15](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NPGQSKA6Rf1MpyS3H8H:-NPGQSKA6Rf1MpyS3H8I:bmuy6jt) ([raw file](https://github.com/starknet-io/starknet-docs/blob/08480fec0be4bc1673f388188ee6dc59ecf68dcb/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L18)):*
> ```AsciiDoc
> For each affected contract, we have a single word encoding (see below the exact format):
> 
> * flag (0 = Storage updates only / 1 = deployed or
> ```

Let's call it "class information flag"



_Code quote:_
```AsciiDoc
flag
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 19 at r15](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NPGQ_J64xL0EhF8JbGx:-NPGQ_J7-AxUXcpjHE-X:bai20i4) ([raw file](https://github.com/starknet-io/starknet-docs/blob/08480fec0be4bc1673f388188ee6dc59ecf68dcb/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L19)):*
> ```AsciiDoc
> 
> * flag (0 = Storage updates only / 1 = deployed or
> replaced), nonce, num_of_storage_updates
> ```

contract was deployed or replaced in this state update



_Code quote:_
```AsciiDoc
* flag (0 = Storage updates only / 1 = deployed or

replaced), nonce, num_of_storage_updates
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 19 at r15](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NPGQeBZCLlDQ0GW-GH-:-NPGQeBZCLlDQ0GW-GH0:b-4zg4d2) ([raw file](https://github.com/starknet-io/starknet-docs/blob/08480fec0be4bc1673f388188ee6dc59ecf68dcb/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L19)):*
> ```AsciiDoc
> 
> * flag (0 = Storage updates only / 1 = deployed or
> replaced), nonce, num_of_storage_updates
> ```

separate bullet point



_Code quote:_
```AsciiDoc
nonce
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 19 at r15](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NPGQgRV6SVlm5A892s4:-NPGQgRW0y4yZioiS8sS:b-4zg4d2) ([raw file](https://github.com/starknet-io/starknet-docs/blob/08480fec0be4bc1673f388188ee6dc59ecf68dcb/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L19)):*
> ```AsciiDoc
> 
> * flag (0 = Storage updates only / 1 = deployed or
> replaced), nonce, num_of_storage_updates
> ```

separate bullet point



_Code quote:_
```AsciiDoc
num_of_storage_updates
```

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, 204 of 204 files at r13, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/285)* status: all files reviewed, 11 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 72 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NOp6DF25QEzHh91cmCn:-NPHjcex7p90tb_ay7Y9:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fe11e6279bb1045a9073b0db9e8a650ee3d70a2c/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L72)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

still there
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
index 6 in the array)
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 75 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NPGR_eK6LzWHeeZ59gn:-NPHjlQJ9e1UGV-P7B3c:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aa35b2c97c0efc1f55e0ce0870cb023b00a5527/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L75)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

In the preview this is a separate point for some reason
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
We will take only the first contract as an exampl
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 16 at r15](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NPGQmgS3_N3p_71_Sqq:-NPI-afi-xjodO3jWYqS:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/08480fec0be4bc1673f388188ee6dc59ecf68dcb/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L16)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

that encodes (reading this now feels weird, as if we're saying "word-encoding" and the sentence abruptly ends)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 18 at r15](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NPGQSKA6Rf1MpyS3H8H:-NPHjMAA8LMlFQnnQRIy:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/08480fec0be4bc1673f388188ee6dc59ecf68dcb/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L18)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Let's call it "class information flag"
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 19 at r15](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NPGQ_J64xL0EhF8JbGx:-NPHjLxDDX64AhvrHCdc:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/08480fec0be4bc1673f388188ee6dc59ecf68dcb/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L19)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

contract was deployed or replaced in this state update
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 19 at r15](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NPGQeBZCLlDQ0GW-GH-:-NPHjWen-sbf748G77ql:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/08480fec0be4bc1673f388188ee6dc59ecf68dcb/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L19)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

separate bullet point
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 19 at r15](https://reviewable.io/reviews/starknet-io/starknet-docs/285#-NPGQgRV6SVlm5A892s4:-NPHjX6g4ouh_TgZoJiS:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/08480fec0be4bc1673f388188ee6dc59ecf68dcb/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L19)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

separate bullet point
</blockquote></details>

Done.

**Pull request closed without merging**
