### PR TITLE
Remove the deploy transaction from the docs as it is no longer suppor…

### PR DESCRIPTION
**Pull request by JameStark**
…ted in the current version

### Description of the Changes

More detailed removal of deploy transaction reference material

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-160/documentation/

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/160)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/160)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 13 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/160#-NJnub956fICJ3QkcGcT:-NJnub96BuBsFegfePi9:b-tw7cd7) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e953fad5645f9b39a9d52bb7172863bdf2f75aaa/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L13)):*
> ```AsciiDoc
> [IMPORTANT]
> ====
> The deploy transaction has now been removed in the current release of StarkNet. To deploy new contract instances, you can use the `deploy` syscall. For more information, see xref:../Contracts/contract-classes.adoc[contract classes].
> ```

If I go here I don't get more relevant information on the topic - I think we should add a section on contracts and account deployment and link to it once we have it



_Code quote:_
```AsciiDoc
For more information, see xref:../Contracts/contract-classes.adoc[contract classes]
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 205 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/160#-NJnuRXkEecz7j0LRnNW:-NJnuRXl7WXBAKDDfJwM:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e953fad5645f9b39a9d52bb7172863bdf2f75aaa/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L205)):*
> ```AsciiDoc
> * `SN_MAIN` for StarkNet's main network.
> * `SN_GOERLI` for StarkNet's public testnet.
> * `SN_GOERLI2` for StarkNet's developer only testnet.
> ```





_Suggestion:_
```AsciiDoc
 's
```

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/160)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 13 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/160#-NJnub956fICJ3QkcGcT:-NJoFIfL1jFtuAAEt-QN:bi2vee2) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e953fad5645f9b39a9d52bb7172863bdf2f75aaa/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L13)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

If I go here I don't get more relevant information on the topic - I think we should add a section on contracts and account deployment and link to it once we have it
</blockquote></details>

Ok, I will remove the link for now and make a note to add a link once we have some more relevant info.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 205 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/160#-NJnuRXkEecz7j0LRnNW:-NJoF4F99p0NAeu7GFqz:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e953fad5645f9b39a9d52bb7172863bdf2f75aaa/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L205)):*
> ```AsciiDoc
> * `SN_MAIN` for StarkNet's main network.
> * `SN_GOERLI` for StarkNet's public testnet.
> * `SN_GOERLI2` for StarkNet's developer only testnet.
> ```

Done.

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/160)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp and @bbrandtom)

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/160)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 13 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/160#-NJnub956fICJ3QkcGcT:-NJsiewf7PbUh8RWh1xy:b-zcjvte) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e953fad5645f9b39a9d52bb7172863bdf2f75aaa/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L13)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Ok, I will remove the link for now and make a note to add a link once we have some more relevant info.
</blockquote></details>

Thanks
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 205 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/160#-NJsilm6CB0miJegXOTM:-NJsilm6CB0miJegXOTN:b-f8bpyr) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ed452cdaab3614dc6700cd756122e0971387e564/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L205)):*
> ```AsciiDoc
> * `SN_MAIN` for StarkNet's main network.
> * `SN_GOERLI` for StarkNet's public testnet.
> * `SN_GOERLI2` for StarkNet's developer's testnet.
> ```

actually, maybe it should be just "developers"?

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/160)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @bbrandtom, and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 205 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/160#-NJsilm6CB0miJegXOTM:-NJzUomsDZRfbuk9BRqR:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ed452cdaab3614dc6700cd756122e0971387e564/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L205)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

actually, maybe it should be just "developers"?
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/160)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @bbrandtom)

**Review by bbrandtom — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/160#-:-NK7lLKTDYoJeiDu5-Qo:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
