### PR TITLE
v0.11.0 - upcoming version changelog

### PR DESCRIPTION
**Pull request by ArielElp**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/275)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/275)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp and @JameStark)

___
*[`components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc` line 245 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/275#-NOO94dM76qm7LmPY141:-NOO94dM76qm7LmPY142:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b094a48cf3e86d57d07e4e43e2ad7111bece52a/components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc#L245)):*
> ```AsciiDoc
> #### State commitment
> 
> The changes elaborated xref:#commitment[above] will be slightly modified as follows:
> ```





_Suggestion:_
```AsciiDoc
The changes elaborated in the xref:#commitment[commitment scheme] has been slightly modified as follows
```
___
*[`components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc` line 249 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/275#-NOO9S1o-LbZfmON8Qix:-NOO9S1p9iXzzY8N0hiP:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b094a48cf3e86d57d07e4e43e2ad7111bece52a/components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc#L249)):*
> ```AsciiDoc
> * The classes tree will be computed with the Poseidon hash function, while the global state tree will continue to use Pedersen
> * The leaves in the classes tree will be `h(compiled_class_hash, leaf_version)` where `leaf_version` is a field added to allow forward compatability and is currently set to 0
> * If the classes tree is none empty, the commitment will be computed by `h(global_tree_root, classes_root, commitment_version)` where `h`
> ```





_Suggestion:_
```AsciiDoc
state commitment
```
___
*[`components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc` line 249 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/275#-NOO9Vku6ep0-VwaQyC-:-NOO9Vkv8CZ9dfW9K_sW:bjbfc7u) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b094a48cf3e86d57d07e4e43e2ad7111bece52a/components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc#L249)):*
> ```AsciiDoc
> * The classes tree will be computed with the Poseidon hash function, while the global state tree will continue to use Pedersen
> * The leaves in the classes tree will be `h(compiled_class_hash, leaf_version)` where `leaf_version` is a field added to allow forward compatability and is currently set to 0
> * If the classes tree is none empty, the commitment will be computed by `h(global_tree_root, classes_root, commitment_version)` where `h`
> ```

What happens if the class tree is empty?
___
*[`components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc` line 255 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/275#-NOO9bExDPlQHdV4ACVe:-NOO9bExDPlQHdV4ACVf:b-uyw70g) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b094a48cf3e86d57d07e4e43e2ad7111bece52a/components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc#L255)):*
> ```AsciiDoc
> #### On-Chain data
> 
> In addition to the changes explained xref:#ocd[here], we will have an additional section for the newly declared (Cairo 1) classes in the block. This section will contain:
> ```

Please change the phrasing to reflect that it has been changed in the doc

**Review by ArielElp — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/275#-:-NOOTKV01M2jWazPTv3V:bnfp4nl)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @bbrandtom and @JameStark)

___
*[`components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc` line 245 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/275#-NOO94dM76qm7LmPY141:-NOOQqfiCHI1wcxO9ZvB:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b094a48cf3e86d57d07e4e43e2ad7111bece52a/components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc#L245)):*
> ```AsciiDoc
> #### State commitment
> 
> The changes elaborated xref:#commitment[above] will be slightly modified as follows:
> ```

Done.
___
*[`components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc` line 249 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/275#-NOO9S1o-LbZfmON8Qix:-NOOQsAo9bbnpzNKzhao:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b094a48cf3e86d57d07e4e43e2ad7111bece52a/components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc#L249)):*
> ```AsciiDoc
> * The classes tree will be computed with the Poseidon hash function, while the global state tree will continue to use Pedersen
> * The leaves in the classes tree will be `h(compiled_class_hash, leaf_version)` where `leaf_version` is a field added to allow forward compatability and is currently set to 0
> * If the classes tree is none empty, the commitment will be computed by `h(global_tree_root, classes_root, commitment_version)` where `h`
> ```

Done.
___
*[`components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc` line 249 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/275#-NOO9Vku6ep0-VwaQyC-:-NOOQv2HDtJv6O-TZkp2:b-it2bl1) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b094a48cf3e86d57d07e4e43e2ad7111bece52a/components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc#L249)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

What happens if the class tree is empty?
</blockquote></details>

it's explained in the main doc, just global state root
___
*[`components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc` line 255 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/275#-NOO9bExDPlQHdV4ACVe:-NOORDkx6weqXbsACtzq:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b094a48cf3e86d57d07e4e43e2ad7111bece52a/components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc#L255)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Please change the phrasing to reflect that it has been changed in the doc
</blockquote></details>

Done.

**Review by bbrandtom — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/275#-:-NOOUxky2-BqGzgJt9Wi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Review by ArielElp — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/275)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Pull request merged**
