### PR TITLE
docs: Improvements to topics on account functions.

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

* Clarify all `__validate*__` functions
* Add account function reference
* Clarify limitations on `__validate*__` functions

This PR is a cleanup of #945, which at some point introduced a lot of unwanted obsolete reversions.

Currently the section [Validate limitations](https://docs.starknet.io/documentation/architecture_and_concepts/Accounts/validate_and_execute/#validate_limitations) doesn't actually list the limitations. This PR fixes that.

### PR Preview URL

[Starknet’s account interface](https://starknet-io.github.io/starknet-docs/pr-1198/documentation/architecture_and_concepts/Accounts/approach/)
[Account interface function reference](https://starknet-io.github.io/starknet-docs/pr-1198/documentation/architecture_and_concepts/Accounts/account_functions/)

### Check List

- [x] Changes have been done against main branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1198)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 23 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-NtuZGBE7pcpnZ1SrDHl:-NtuZGBE7pcpnZ1SrDHm:b-1kcxp5) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L23)):*
> ```AsciiDoc
> You can only use the `+__validate_deploy__+` function in an account contract to validate the `DEPLOY_ACCOUNT` transaction for that same contract.
> ====
> | `+__constructor__+` | If an account does not define a `+__constructor__+` function, the sequencer uses a default `+__constructor__+` function, which is empty.
> ```

no `_`.



_Suggestion:_
```AsciiDoc
constructor
```

**Comment by ArniStarkware** [comment]
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 23 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-NtuZNX-1FjbecIoqQi3:-NtuZNX-1FjbecIoqQi4:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L23)):*
> ```AsciiDoc
> You can only use the `+__validate_deploy__+` function in an account contract to validate the `DEPLOY_ACCOUNT` transaction for that same contract.
> ====
> | `+__constructor__+` | If an account does not define a `+__constructor__+` function, the sequencer uses a default `+__constructor__+` function, which is empty.
> ```





_Suggestion:_
```AsciiDoc
| `+constructor+` | If an account does not define a `+constructor+` function, the sequencer uses a default `+constructor+` function, which is empty.
```

**Comment by ArniStarkware** [comment]
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 23 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-Ntu_MY_-P3assXSBX4K:-Ntu_MY_-P3assXSBX4L:b-8naql9) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L23)):*
> ```AsciiDoc
> You can only use the `+__validate_deploy__+` function in an account contract to validate the `DEPLOY_ACCOUNT` transaction for that same contract.
> ====
> | `+__constructor__+` | If an account does not define a `+__constructor__+` function, the sequencer uses a default `+__constructor__+` function, which is empty.
> ```

About the constructor - I like the fact it is on this page.
If you can say that any contract has a constructor. As stated here, it is defined explicitly or used as the default constructor.



_Code quote:_
```AsciiDoc
| `+__constructor__+` | If an account does not define a `+__constructor__+` function, the sequencer uses a default `+__constructor__+` function, which is empty.
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1198)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @stoobie)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 30 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-Ntu_tPf6WZazLqFlk-r:-Ntu_tPgANUDsoWSinCx:b-pwoa18) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L30)):*
> ```AsciiDoc
> For an `INVOKE` transaction, after successfully completing validation, the sequencer calls the `+__execute__+` function with the fields of the transaction request.
> 
> For a `DEPLOY_ACCOUNT` transaction, the sequencer calls the `+__constructor__+` function with the fields of the transaction request. Then, after successfully completing validation, the deployment is finalized.
> ```

is it clear that `completing validation` means running the `__validate_deploy__` entry point?



_Suggestion:_
```AsciiDoc
For a `DEPLOY_ACCOUNT` transaction, the sequencer calls the `+constructor+` function with the parameters supplied to the transaction. Then, after successfully completing validation, the deployment is finalized.
```
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 55 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-NtuaSq74-UnR-Rtey8i:-NtuaSq74-UnR-Rtey8j:b3kre) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L55)):*
> ```AsciiDoc
> The limitations listed here apply to the following validation functions:
> 
> * `+__validate__+`, `+__validate_deploy__+`, and `+__validate_declare__+`
> ```

?



_Suggestion:_
```AsciiDoc
* `+__validate__+`, `+__validate_deploy__+`, and `+__validate_declare__+`.
```
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 73 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-NtuanttCsIX-BNWAHiJ:-NtuanttCsIX-BNWAHiK:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L73)):*
> ```AsciiDoc
> * Access is restricted to `sequencer_address` in the `get_execution_info` syscall. The syscall returns zero values for `sequencer_address`.
> * The values of `block_number` and `block_timestamp` in the `get_execution_info` syscall are modified as follows:
> ** `block_timestamp` returns the hour, rounded down.
> ```





_Suggestion:_
```AsciiDoc
** `block_timestamp` returns the time (in UTC), rounded to the latest hour.
```
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 196 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-NtubiPg1zm_BNJfpps3:-NtubiPg1zm_BNJfpps4:b-nlwxdd) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L196)):*
> ```AsciiDoc
> .Example
> 
> Notice how the signature of `+__validate_deploy__+` is structured to consider the signature of the constructor:
> ```

Is this sentence + example readable? 

Is it clear that the `__validate_deploy__`'s parameters should be: `self`, `class_hash`, `contract_address_salt` + "the non-self arguments of the constructor"?
Is it written somewhere else?



_Code quote:_
```AsciiDoc
.Example

Notice how the signature of `+__validate_deploy__+` is structured to consider the signature of the constructor:
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-:-NtvBB659bDIQRUYj6he:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @stoobie)

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1198)* status: all files reviewed, 1 unresolved discussion (waiting on @stoobie)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 23 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-NtuZNX-1FjbecIoqQi3:-Ntv8JON5EvM86Z2rIKx:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L23)):*
> ```AsciiDoc
> You can only use the `+__validate_deploy__+` function in an account contract to validate the `DEPLOY_ACCOUNT` transaction for that same contract.
> ====
> | `+__constructor__+` | If an account does not define a `+__constructor__+` function, the sequencer uses a default `+__constructor__+` function, which is empty.
> ```

Done.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 23 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-NtuZGBE7pcpnZ1SrDHl:-Ntv8L3fDvcVQlzqBDnV:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L23)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

no `_`.
</blockquote></details>

Done.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 23 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-Ntu_MY_-P3assXSBX4K:-NtvDTuy7F6Zx5Sf5XMd:b-qsvnoa) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L23)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

About the constructor - I like the fact it is on this page.
If you can say that any contract has a constructor. As stated here, it is defined explicitly or used as the default constructor.
</blockquote></details>

Done. PTAL.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 30 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-Ntu_tPf6WZazLqFlk-r:-Ntuos5M0cjt23aZrVuz:bmfuxxu) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L30)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

is it clear that `completing validation` means running the `__validate_deploy__` entry point?
</blockquote></details>

PTAL now. I added the DECLARE tx.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 55 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-NtuaSq74-UnR-Rtey8i:-Ntutlkb1MaCl4ymvyB9:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L55)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 73 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-NtuanttCsIX-BNWAHiJ:-NtuwQh1CxZlIzQeitPQ:b-k7lo3o) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L73)):*
> ```AsciiDoc
> * Access is restricted to `sequencer_address` in the `get_execution_info` syscall. The syscall returns zero values for `sequencer_address`.
> * The values of `block_number` and `block_timestamp` in the `get_execution_info` syscall are modified as follows:
> ** `block_timestamp` returns the hour, rounded down.
> ```

Done. I changed "latest" to "most recent".

**Comment by ArniStarkware** [comment]
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 196 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-NtubiPg1zm_BNJfpps3:-Ntyx57C0p1O6F1Ntb1G:bko053e) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7f461fa0954251043773ec00bf12cc9446597eb9/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L196)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is this sentence + example readable? 

Is it clear that the `__validate_deploy__`'s parameters should be: `self`, `class_hash`, `contract_address_salt` + "the non-self arguments of the constructor"?
Is it written somewhere else?
</blockquote></details>

It is non-blocking in my opinion.

**Review by ArniStarkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1198)* status: all files reviewed, 1 unresolved discussion (waiting on @stoobie)

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1198)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @stoobie)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 223 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-NtzIidP14NxRyNWZXB0:-NtzIidQ97SN4NRhN9MU:b-idkea8) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bba5584c70433dae79c56afc363d6feeefd30310/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L223)):*
> ```AsciiDoc
>      self.only_protocol();  // Ensures only the Starknet protocol can call
>       // Even though public_key is provided, it uses the one stored from the constructor
>       self.validate_transaction()  // Applies the same validation logic
> ```

I did not understand the comments.

Should there be more periods?
What are you trying to say?



_Code quote:_
```AsciiDoc
     self.only_protocol();  // Ensures only the Starknet protocol can call
      // Even though public_key is provided, it uses the one stored from the constructor
      self.validate_transaction()  // Applies the same validation logic
```

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1198)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc` line 223 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-NtzIidP14NxRyNWZXB0:-Ntzse3kCm3fbYMRvfGm:b-acgkvf) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bba5584c70433dae79c56afc363d6feeefd30310/components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc#L223)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I did not understand the comments.

Should there be more periods?
What are you trying to say?
</blockquote></details>

I removed the comments and that part of the function, as we discussed

**Review by ArniStarkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1198#-:-Ntzt3Qf-V31VYIl2LWY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stoobie)

**Pull request merged**
