### PR TITLE
Add a version of DA for pre and post v0.11.0

### PR DESCRIPTION
**Pull request by JameStark**
### Description of the Changes

Add a version of DA for pre and post v0.11.0

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-334/documentation/architecture_and_concepts/Data_Availability/on-chain-data/

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334)* status: all files reviewed, 4 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 124 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPJ-3QL15SU1aa9oWHU:-NPJ-3QL15SU1aa9oWHV:b-qqli62) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ee991e97a731fa6776f3e95e43ef5753561610df/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L124)):*
> ```AsciiDoc
> The state diffs contain information on every contract whose storage was updated and additional information on contract deployments.
> 
> For each affected contract, we have a single word-encoding that encodes:
> ```

a single word that encodes



_Code quote:_
```AsciiDoc
single word-encoding that encodes
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 124 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPJ0IF473Zlz5pCzKpp:-NPJ0IF473Zlz5pCzKpq:b-n1xuhc) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ee991e97a731fa6776f3e95e43ef5753561610df/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L124)):*
> ```AsciiDoc
> The state diffs contain information on every contract whose storage was updated and additional information on contract deployments.
> 
> For each affected contract, we have a single word-encoding that encodes:
> ```

let's break after "For each affected contract, we have:", and add another indent level:
1. the contract address (I forgot this previously)
2. a single word that encodes:
2.1 class information flag...
2.2 new nonce
2.3 number of storage updates
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 159 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPJ-prC1d-vm7xBFtKN:-NPJ-prC1d-vm7xBFtKO:be0x1z5) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ee991e97a731fa6776f3e95e43ef5753561610df/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L159)):*
> ```AsciiDoc
> [source,json]
> ----
> [
> ```

to match the description, let's change this array to:

1
2019172390095051323869047481075102003731246132997057518965927979101413600827,
18446744073709551617
100
200
1
1351148242645005540004162531550805076995747746087542030095186557536641755046
558404273560404778508455254030458021013656352466216690688595011803280448032
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 190 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPJ1Ms-DXUnpaFx_aK5:-NPJ1Ms-DXUnpaFx_aK6:b5iy0fz) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ee991e97a731fa6776f3e95e43ef5753561610df/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L190)):*
> ```AsciiDoc
> ----
> 
> * The first element, `5`, is the number of contracts whose state was updated. We will take only
> ```

we can have a much shorter description for this now:

* The first element, `1`, is the number of contract whose state was updated
* The second element, `2019172390095051323869047481075102003731246132997057518965927979101413600827,` is the address of the first (and only) contract whose state changed
* The third element, `18446744073709551617`, which is stem:[$2^{64}+1$] encodes the following:
* * flag = 0, that is, the contract was not just deployed or replaced, so we shouldn't treat the next word as the class hash
* * the new nonce is 1
* * one storage cell was updated
* The next two elements, `100` and `200` encode the storage update (the value of key `100` was set to `200`)
* Next we have the new declare section: `1` means the we had a single declare v2 [insert link to declare v2] in this state update, and the next two elements encode the class hash [insert link to class hash] and compiled class hash [insert link to what to expect in the upcoming versions page, since we don't have something for compiled class yet] of the declared class



_Code quote:_
```AsciiDoc
* The first element, `5`, is the number of contracts whose state was updated. We will take only
the first contract as an example.

* The next two elements describe a single contract deployment with the following parameters:
** The word encoding the flag
** Updated nonce
** Number of storage updates
+
----
18446744073709551617
----

One update (indicated by the cell at index 8):
which is stem:[$2^{64}+1$], thus:

* flag = 0, so the contract class isn't replaced, nor was the contract just deployed, i.e. there
is no need to specify the class hash
* The new contract nonce is 1
* One storage key is updated:
** The value at key 5 was changed to 102.
```

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 124 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPJ-3QL15SU1aa9oWHU:-NPM1dn53UA57oR-nvtq:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ee991e97a731fa6776f3e95e43ef5753561610df/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L124)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

a single word that encodes
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 124 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPJ0IF473Zlz5pCzKpp:-NPM21VvAjLvd2kjBodH:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ee991e97a731fa6776f3e95e43ef5753561610df/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L124)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

let's break after "For each affected contract, we have:", and add another indent level:
1. the contract address (I forgot this previously)
2. a single word that encodes:
2.1 class information flag...
2.2 new nonce
2.3 number of storage updates
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
s information f
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 159 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPJ-prC1d-vm7xBFtKN:-NPM2Ohu0cggPp8swGJt:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ee991e97a731fa6776f3e95e43ef5753561610df/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L159)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

to match the description, let's change this array to:

1
2019172390095051323869047481075102003731246132997057518965927979101413600827,
18446744073709551617
100
200
1
1351148242645005540004162531550805076995747746087542030095186557536641755046
558404273560404778508455254030458021013656352466216690688595011803280448032
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 190 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPJ1Ms-DXUnpaFx_aK5:-NPM3RRi7sCodWYiI0xM:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ee991e97a731fa6776f3e95e43ef5753561610df/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L190)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

we can have a much shorter description for this now:

* The first element, `1`, is the number of contract whose state was updated
* The second element, `2019172390095051323869047481075102003731246132997057518965927979101413600827,` is the address of the first (and only) contract whose state changed
* The third element, `18446744073709551617`, which is stem:[$2^{64}+1$] encodes the following:
* * flag = 0, that is, the contract was not just deployed or replaced, so we shouldn't treat the next word as the class hash
* * the new nonce is 1
* * one storage cell was updated
* The next two elements, `100` and `200` encode the storage update (the value of key `100` was set to `200`)
* Next we have the new declare section: `1` means the we had a single declare v2 [insert link to declare v2] in this state update, and the next two elements encode the class hash [insert link to class hash] and compiled class hash [insert link to what to expect in the upcoming versions page, since we don't have something for compiled class yet] of the declared class
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp)

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334)* status: all files reviewed, 5 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 130 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMpX_x8o8nOnlPAgoc:-NPMpX_x8o8nOnlPAgod:b31v9sb) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L130)):*
> ```AsciiDoc
> 
> ** class information flag (0 = Storage updates only / 1 = contract was deployed or replaced in
> this state update)
> ```

lets's add (in the same bullet point):

when this flag is on, we will have an additional word before the storage updates section, which contains the new class hash
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 139 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMqZXu9GYs9Vo9uSqu:-NPMqZXu9GYs9Vo9uSqv:b-acxx25) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L139)):*
> ```AsciiDoc
> [stem]
> ++++
> \underbrace{0\cdots1}_{\text{127 bits}} |\underbrace{\text{class information flag}}_{\text{1 bit}} |
> ```

this should be 0



_Code quote:_
```AsciiDoc
1
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 179 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMqJC46fBx5mNlBZYi:-NPMqJC46fBx5mNlBZYj:b-vj6gpw) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L179)):*
> ```AsciiDoc
> * The first element, `1`, is the number of contract whose state was updated
> * The second element, `2019172390095051323869047481075102003731246132997057518965927979101413600827`, is the address of the first (and only) contract whose state changed
> * The third element, `18446744073709551617`, which is stem:[$2^{64}+1$] encodes the following:
> ```

add comma after stem
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 186 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMpDi05pZ0KEEkohc1:-NPMpDi1Ai749XpamnFo:bevh3re) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L186)):*
> ```AsciiDoc
> to `200`)
> * Next we have the new declare section: `1`
> means the we had a single xref:documentation:architecture_and_concepts:Blocks/transactions.adoc#_declare_transaction_version_2[declare v2] in this state update, and the next two elements
> ```

something wrong with the id here



_Code quote:_
```AsciiDoc
_declare_transaction_version_2[
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 186 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMpKst-rka3aRk05Lg:-NPMpKst-rka3aRk05Lh:bb7p4x8) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L186)):*
> ```AsciiDoc
> to `200`)
> * Next we have the new declare section: `1`
> means the we had a single xref:documentation:architecture_and_concepts:Blocks/transactions.adoc#_declare_transaction_version_2[declare v2] in this state update, and the next two elements
> ```

that



_Code quote:_
```AsciiDoc
the
```

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334)* status: all files reviewed, 5 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 130 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMpX_x8o8nOnlPAgoc:-NPMtkRfBxVfIVRT1NsH:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L130)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

lets's add (in the same bullet point):

when this flag is on, we will have an additional word before the storage updates section, which contains the new class hash
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 139 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMqZXu9GYs9Vo9uSqu:-NPMugab2dVEbQ0fi1wn:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L139)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

this should be 0
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 179 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMqJC46fBx5mNlBZYi:-NPMu0XoDQhTcM_W5cqy:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L179)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

add comma after stem
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 186 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMpDi05pZ0KEEkohc1:-NPMuERT0tqHxKkIciuW:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L186)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

something wrong with the id here
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 186 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMpKst-rka3aRk05Lg:-NPMuG8n5lsygjKauplp:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L186)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

that
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334)* status: all files reviewed, 5 unresolved discussions (waiting on @ArielElp)

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334)* status: all files reviewed, 2 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 139 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMqZXu9GYs9Vo9uSqu:-NPMwLGREYxAM5S50vV_:bymckz2) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L139)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

with cdots, i.e. I want it to be clear that these are 127 zeros, so 0...0
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 186 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMpDi05pZ0KEEkohc1:-NPMwnv101P9vr7m85E7:b-xx32uw) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L186)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

hhmm link broken still

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 139 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMqZXu9GYs9Vo9uSqu:-NPRAX5l3U0jh1bjsjJY:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L139)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

with cdots, i.e. I want it to be clear that these are 127 zeros, so 0...0
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 186 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPMpDi05pZ0KEEkohc1:-NPRAkYHEZYGkX7BBrSp:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/bd145e08bb476eb8593c63e567a5f999ea0f9f1f/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L186)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

hhmm link broken still
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp)

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334)* status: all files reviewed, 2 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 140 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPRE4vM4TKlEsCVeIiH:-NPRE4vN4G6iVCsR67PD:b-snlw64) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f02915f43506ccbf2318f1e701d5b26a7cf3dbfe/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L140)):*
> ```AsciiDoc
> [stem]
> ++++
> \$\underbrace{0\cdots0}_{\text{127 bits}}|\underbrace{\text{class information flag}}_{\text{1
> ```

remove $, I think you don't need it in stem environment (it's visible on the page)



_Code quote:_
```AsciiDoc
$
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 143 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPREgdSA1T8uie-yhRh:-NPREgdSA1T8uie-yhRi:bjc4zx1) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f02915f43506ccbf2318f1e701d5b26a7cf3dbfe/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L143)):*
> ```AsciiDoc
> bit}} |
> \underbrace{\text{new nonce}}_{\text{64 bits}} |
> \underbrace{\text{# of storage updates}}_{\text{64 bits}}
> ```

add _{\text{LSB}} (same as the pre 0.11 section)

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 140 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPRE4vM4TKlEsCVeIiH:-NPRFOZa0gy08SQU29WO:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f02915f43506ccbf2318f1e701d5b26a7cf3dbfe/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L140)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

remove $, I think you don't need it in stem environment (it's visible on the page)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc` line 143 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-NPREgdSA1T8uie-yhRh:-NPRSqya4wqORClHga-C:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f02915f43506ccbf2318f1e701d5b26a7cf3dbfe/components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc#L143)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

add _{\text{LSB}} (same as the pre 0.11 section)
</blockquote></details>

Done.

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/334#-:-NPRWcqp-YAF_0ikhjMn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Pull request merged**
