### PR TITLE
feat(docs):add pyth to starknet docs

### PR DESCRIPTION
**Pull request by mariobern**
### Description of the Changes

Hi all, Mario from Pyth here. Would like to create an oracle section within the docs and feature Pyth there.

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-1375/ .

### Check List

- [x] Changes have been done against main branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

### CODE REVIEW

**Comment by LandauRaz** [comment]
Hey @mariobern, thanks for your contribution!
An oracles section can be great, but we typically use tables in the "Tools and resources" section and refrain from adding guides (there will soon be a "Guides" section for that, although this guide looks identical to https://docs.pyth.network/price-feeds/use-real-time-data/starknet so just adding a link would probably suffice).
Please LMK If you prefer to refactor this PR accordingly or open a new PR (in which case I'll close this one).

**Comment by mariobern** [comment]
hi @LandauRaz good to know

though I can't seem to find the tables you mentioned, could you point me to them please?

and yeah, we can just attach the link and add the full guide to Guides section once it's live

**Comment by LandauRaz** [comment]
Sounds good!
Here are some examples for such tables:

1. https://github.com/starknet-io/starknet-docs/blob/main/components/Starknet/modules/tools/pages/api-services.adoc displayed at: https://docs.starknet.io/tools/api-services/
2. https://github.com/starknet-io/starknet-docs/blob/main/components/Starknet/modules/tools/pages/ref-block-explorers.adoc displayed at: https://docs.starknet.io/tools/ref-block-explorers/
3. https://github.com/starknet-io/starknet-docs/blob/main/components/Starknet/modules/tools/pages/data-indexers.adoc displayed at: https://docs.starknet.io/tools/data-indexers/
4. https://github.com/starknet-io/starknet-docs/blob/main/components/Starknet/modules/tools/pages/audit.adoc displayed at: https://docs.starknet.io/tools/audit/

**Comment by mariobern** [comment]
@LandauRaz thanks for the links! I have revamped the existing oracle section to a table just now. Kindly review and let me know if I miss anything

**Review by LandauRaz — APPROVED** [review]

**Comment by LandauRaz** [comment]
You're good 🙂 Thanks for the contribution!

**Pull request merged**
