### PR TITLE
End of life and deprecated features

### PR DESCRIPTION
**Pull request by JameStark**
### Description of the Changes

Create a page for End of Life and Deprecated Features

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-159/documentation/end_of_life_and_deprecated_features/

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/159)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/159)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp and @JameStark)

___
*[`components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 2 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/159#-NJnytzs0J4tuJUL_g2k:-NJnytzt7zhS3l5-irof:b-rnoynn) ([raw file](https://github.com/starknet-io/starknet-docs/blob/c31176a3ce91c3632a047f577b8d7c8668dd5655/components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L2)):*
> ```AsciiDoc
> [id="eol"]
> = End of life and obsolete features
> ```

missing some place to list what has been deprecated and when we plan to remove it (if we have a specified version yet)
___
*[`components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 11 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/159#-NJnxjzG9zBgLy6ynenz:-NJnxjzHCQdewimINGuk:b-dlga9d) ([raw file](https://github.com/starknet-io/starknet-docs/blob/c31176a3ce91c3632a047f577b8d7c8668dd5655/components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L11)):*
> ```AsciiDoc
> 
> |Deprecated|Feature or capability is no longer actively supported. It may still work, but future fixes or enhancements are unlikely. 
> |Obsolete|Feature or capability has been removed from StarkNet. 
> ```

here you use Obsolete and below you use End of life - is this on purpose?



_Code quote:_
```AsciiDoc
Obsolete
```
___
*[`components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 19 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/159#-NJnync3AoNbkkRnPV6r:-NJnync41aMjRGerJcpI:bas8o5r) ([raw file](https://github.com/starknet-io/starknet-docs/blob/c31176a3ce91c3632a047f577b8d7c8668dd5655/components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L19)):*
> ```AsciiDoc
> [cols="1,3"]
> |===
> |Status|Description 
> ```

Maybe add a column of "name"

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/159)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 11 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/159#-NJnxjzG9zBgLy6ynenz:-NJoH7nf-fqJleXc87tz:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/c31176a3ce91c3632a047f577b8d7c8668dd5655/components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L11)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

here you use Obsolete and below you use End of life - is this on purpose?
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 19 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/159#-NJnync3AoNbkkRnPV6r:-NJoH8w1DudryixbCH_E:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/c31176a3ce91c3632a047f577b8d7c8668dd5655/components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L19)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Maybe add a column of "name"
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/159)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 2 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/159#-NJnytzs0J4tuJUL_g2k:-NJoHO2N2z1I3TaJRVOX:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/c31176a3ce91c3632a047f577b8d7c8668dd5655/components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L2)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

missing some place to list what has been deprecated and when we plan to remove it (if we have a specified version yet)
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/159)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp and @bbrandtom)

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/159)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @JameStark)

___
*[`components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 2 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/159#-NJnytzs0J4tuJUL_g2k:-NJsmy6VDre0UdqKfx8G:b-939bnu) ([raw file](https://github.com/starknet-io/starknet-docs/blob/c31176a3ce91c3632a047f577b8d7c8668dd5655/components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L2)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the list :thinking:

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/159)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/159)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 2 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/159#-NJnytzs0J4tuJUL_g2k:-NJyEvbI-r-DHSRhThnR:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/c31176a3ce91c3632a047f577b8d7c8668dd5655/components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L2)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I don't see the list :thinking: 
</blockquote></details>

Done.

**Review by bbrandtom — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/159#-:-NK7lAfk4P-0DN3cPj3m:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
