### PR TITLE
chore: normalize file path

### PR DESCRIPTION
**Pull request by ylmin**
### Description of the Changes

- normalize File Path

### PR Preview URL

No

### Check List

- [x] Changes have been done against dev branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/910)

### CODE REVIEW

**Comment by stoobie** [comment]
> ### Description of the Changes
> * normalize File Path
> 
@ylmin Can you please provide more information? What is the problem that you are trying to fix? How does this change fix the problem?

**Comment by ylmin** [comment]
> > ### 变更说明
> > 
> > * 标准化文件路径
> 
> @ylmin您能提供更多信息吗？您想要解决的问题是什么？此更改如何解决问题？

**Comment by ylmin** [comment]
> > ### Description of the Changes
> > 
> > * normalize File Path
> 
> @ylmin Can you please provide more information? What is the problem that you are trying to fix? How does this change fix the problem?

Absolute paths vs Relative paths: path.resolve(__dirname, './file.js') returns the absolute path of 'file.js', while './file.js' returns a relative path relative to the current working directory.

Ensuring Reliable File Positioning: path.resolve(__dirname, './file.js') ensures that the position of the file is relative to the current module file, which is not affected by the startup path of the Node.js application. On the other hand, directly using './file.js' as a relative path might be affected by the startup path.

Therefore, using path.resolve(__dirname, './file.js') can more reliably obtain the absolute path of a file.

**Comment by ylmin** [comment]
> > ### Description of the Changes
> > 
> > * normalize File Path
> 
> @ylmin Can you please provide more information? What is the problem that you are trying to fix? How does this change fix the problem?

Understood! Here's the difference between using path.resolve with and without __dirname:

When using path.resolve without __dirname, the function will resolve the path based on the current working directory (CWD) of the Node.js process. In other words, if you provide a relative path without __dirname, the function will assume that the path is relative to the CWD.

On the other hand, when using path.resolve with __dirname, the function will resolve the path based on the directory where the current module file is located. In other words, if you provide a relative path with __dirname, the function will assume that the path is relative to the directory where the module file is located.

The difference lies in how the function interprets the relative path. Without __dirname, the function assumes that the path is relative to the CWD, which may not be the desired behavior in some cases. For example, if you have a folder structure like this:


my_project/
│    index.js
│    node_modules/
│    lib/
└── main.js
If you call path.resolve(__dirname, '../lib/my_file.js'), without using __dirname, the function will resolve the path to /./lib/my_file.js, which may not be what you intended. However, if you use path.resolve(__dirname, 'my_file.js'), the function will resolve the path to my_file.js in the lib folder, which is the desired behavior.

In summary, using path.resolve with __dirname can help you write more predictable and robust code by ensuring that the relative path is resolved based on the correct directory.

**Comment by stoobie** [comment]
@ylmin Can you suggest how I can test this to make sure it doesn't break anything? Sorry, I'm not much of a JS dev.

**Pull request merged**
