### PR TITLE
Move transaction example below 1st table to l1-l2

### PR DESCRIPTION
**Pull request by JameStark**
### Description of the Changes

Separate description of messaging & txn on l2-l1

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-154/documentation/architecture_and_concepts/L1-L2_Communication/messaging-mechanism/

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0aoxmCNg9htp5t8pT:-NJ0aoxmCNg9htp5t8pU:bjskr7g) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
> ```AsciiDoc
> For completeness, we describe the precise structure of both the message as it appears on L1 and the induced transaction as it appears on L2.
> 
> NOTE: As the message being sent needs to be written to L1 storage there is always a fixed 20k gas cost associated with sending L2 to L1 messages.
> ```

hash of the message



_Code quote:_
```AsciiDoc
message
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0atU9BwtBPMEusdk2:-NJ0atU9BwtBPMEusdk3:bw9ynbg) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
> ```AsciiDoc
> For completeness, we describe the precise structure of both the message as it appears on L1 and the induced transaction as it appears on L2.
> 
> NOTE: As the message being sent needs to be written to L1 storage there is always a fixed 20k gas cost associated with sending L2 to L1 messages.
> ```

add (in the StarkNet Core contract)



_Code quote:_
```AsciiDoc
storage
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0b-CW8-GQZo01NIyT:-NJ0b-CW8-GQZo01NIyU:bvua691) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
> ```AsciiDoc
> For completeness, we describe the precise structure of both the message as it appears on L1 and the induced transaction as it appears on L2.
> 
> NOTE: As the message being sent needs to be written to L1 storage there is always a fixed 20k gas cost associated with sending L2 to L1 messages.
> ```

An L2 to L1 message



_Code quote:_
```AsciiDoc
L2 to L1 messages
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0b36H5EDGw-g7Ohas:-NJ0b36H5EDGw-g7Ohat:b7jrunq) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
> ```AsciiDoc
> For completeness, we describe the precise structure of both the message as it appears on L1 and the induced transaction as it appears on L2.
> 
> NOTE: As the message being sent needs to be written to L1 storage there is always a fixed 20k gas cost associated with sending L2 to L1 messages.
> ```

This note is relevant for L2-->L1 messages (L1-->L2 messages have a different cost, you start by writing something to L1, and once the tx is done on L2 and is proven, you reset the storage on the core contract, so you're paying for an update, which is cheaper)



_Code quote:_
```AsciiDoc
NOTE
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 146 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0aZpJAnWuRHwP9jDc:-NJ0aZpJAnWuRHwP9jDd:bcrk1wu) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L146)):*
> ```AsciiDoc
> | Version        | ContractAddress | Selector             | Calldata       | Nonce          |
> 
> | `FieldElement` | `FieldElement`  | `List+++<FieldElement>+++` | `FieldElement` | `FieldElement` |
> ```

The selector is just a field element (it's a mistake on the docs currently)



_Code quote:_
```AsciiDoc
`List+++<FieldElement>+++`
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 146 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0aeWY4nHtrSvyLeyJ:-NJ0aeWZBhtcVWzMI33R:bj5de2r) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L146)):*
> ```AsciiDoc
> | Version        | ContractAddress | Selector             | Calldata       | Nonce          |
> 
> | `FieldElement` | `FieldElement`  | `List+++<FieldElement>+++` | `FieldElement` | `FieldElement` |
> ```

This should change to List<FieldElement>



_Code quote:_
```AsciiDoc
`FieldElement`
```

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 146 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0aeWY4nHtrSvyLeyJ:-NJ0bWYmDge7O_h7IwcX:bs0vc7l) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L146)):*
> change
List<FieldElement>

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0aoxmCNg9htp5t8pT:-NJ4Z_GNBNwpmoEM66Ig:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

hash of the message
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0atU9BwtBPMEusdk2:-NJ4ZpV5DP_lHslntd3U:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

add (in the StarkNet Core contract)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0b-CW8-GQZo01NIyT:-NJ4Zplo7JPv6Qc2RWEK:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

An L2 to L1 message
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 146 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0aZpJAnWuRHwP9jDc:-NJ4_5pCE_8zDtGizYRf:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L146)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

The selector is just a field element (it's a mistake on the docs currently)
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0b36H5EDGw-g7Ohas:-NJ4fxKJDKIu_x2zPY7q:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

This note is relevant for L2-->L1 messages (L1-->L2 messages have a different cost, you start by writing something to L1, and once the tx is done on L2 and is proven, you reset the storage on the core contract, so you're paying for an update, which is cheaper)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 146 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0bcIk0AtadxmK7fCK:-NJ4cg9KA7avSYI38uKv:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L146)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

This should change to List<FieldElement>
</blockquote></details>

Done.

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0aoxmCNg9htp5t8pT:-NJAGF-nEiclnEYU24Xi:btjckwa) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry I didn't specify it correctly, we specify the entire message structure (not only the hash), I meant to add "hash of the" here: 

NOTE: As the hash of the message being sent needs...
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0b36H5EDGw-g7Ohas:-NJAGpCz1kzk-UvIG4oh:b-ifmh83) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No need to add this here (this is explained elsewhere), I meant moving the note to the L2->L1 section
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 146 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0bcIk0AtadxmK7fCK:-NJAHBYPAz-5tnQvuvsB:b-zeo2x0) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L146)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Version is a FieldElement
Calldata is List<FieldElement>

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 146 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0bcIk0AtadxmK7fCK:-NJAibj4A-DzNERMluX7:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L146)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Version is a FieldElement
Calldata is List<FieldElement>
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0aoxmCNg9htp5t8pT:-NJAjGVH4khfqFFMWgxN:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Sorry I didn't specify it correctly, we specify the entire message structure (not only the hash), I meant to add "hash of the" here: 

NOTE: As the hash of the message being sent needs...
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0b36H5EDGw-g7Ohas:-NJAjiGCDKc0Tld-NzfW:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

No need to add this here (this is explained elsewhere), I meant moving the note to the L2->L1 section
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp)

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 114 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0aoxmCNg9htp5t8pT:-NJEmiRj6tzJxirpWxuv:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L114)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Remove the "hash of the" from the above. 
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc` line 146 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-NJ0bcIk0AtadxmK7fCK:-NJEo5D3AH_7t3DGJPec:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9d2ef0731ac7537730fa21856c85315133418cf8/components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc#L146)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

List = List<FieldElement> (we must specify the type of the elements in the list)
</blockquote></details>

Done.

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154#-:-NJErEmu1WqLbAch1OuT:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved

**Review by ArielElp — DISMISSED** [review]
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Pull request merged**
