### PR TITLE
Correct formula under state commitment

### PR DESCRIPTION
**Pull request by JameStark**
### Description of the Changes

https://starknet-io.github.io/starknet-docs/pr-174/documentation/

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/174)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/174)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bbrandtom and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/State/starknet-state.adoc` line 47 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/174#-NKO5uwL2ilu7lW_-pbJ:-NKO5uwL2ilu7lW_-pbK:bfv7fzs) ([raw file](https://github.com/starknet-io/starknet-docs/blob/5a0c814d36078e3b2e5d64f178646a6830ec36b9/components/StarkNet/modules/architecture_and_concepts/pages/State/starknet-state.adoc#L47)):*
> ```AsciiDoc
> 
> * stem:[$\text{class_hash}$] is the hash of the contract's definition discussed xref:../Contracts/contract-hash.adoc[here]
> * stem:[$\text{storage_root}$] is the root of another Merkle-Patricia tree of height 251 that is constructed from the contract's storage
> ```

Insert a bullet boint below:

* nonce is the current nonce of the contract



_Code quote:_
```AsciiDoc
*
```

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/174)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/State/starknet-state.adoc` line 47 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/174#-NKO5uwL2ilu7lW_-pbJ:-NKOK1E90NBP0DGWJC-L:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/5a0c814d36078e3b2e5d64f178646a6830ec36b9/components/StarkNet/modules/architecture_and_concepts/pages/State/starknet-state.adoc#L47)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Insert a bullet boint below:

* nonce is the current nonce of the contract
</blockquote></details>

Done.

**Review by ArielElp — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/174)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom)

**Review by ArielElp — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/174#-:-NKOKVwi4c8_6rsy-vQn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom)

**Review by JameStark — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/174#-:-NKOLO7xDYtmD94qJako:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom)

**Pull request merged**
