### PR TITLE
docs: Starkli CLI addition

### PR DESCRIPTION
**Pull request by JameStark**
### Description of the Changes

Deprecating Starknet CLI and replacing it with Starkli CLI.

### PR Preview URL
https://starknet-io.github.io/starknet-docs/pr-696/documentation/tools/CLI/starkli/

### Check List

- [x] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/696)

### CODE REVIEW

**Review by EvyatarO — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/696)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @JameStark)

___
*[`components/Starknet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 21 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/696#-N_iVQGT9bKQ_mUM520P:-N_iVQGT9bKQ_mUM520Q:brtzxtp) ([raw file](https://github.com/starknet-io/starknet-docs/blob/74355f30a05f89eb6e90f67d1732ad209af3f1f3/components/Starknet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L21)):*
> ```AsciiDoc
> |===
> |Name|Description
> |Starknet CLI | The Starknet CLI has been deprecated and replaced by xref:tools:CLI/starkli.adoc[Starkli].
> ```

Maybe it's best to write "deprecates soon", since our guides still using the old CLI. We'll write deprecated once we'll update the guides in the docs.
___
*[`components/Starknet/modules/tools/pages/CLI/commands.adoc` line 6 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/696#-N_iV1IbE997JHuZzlok:-N_iV1Ic24h7U1LJWQt8:brtzxtp) ([raw file](https://github.com/starknet-io/starknet-docs/blob/74355f30a05f89eb6e90f67d1732ad209af3f1f3/components/Starknet/modules/tools/pages/CLI/commands.adoc#L6)):*
> ```AsciiDoc
> [WARNING]
> ====
> The Starknet CLI is now deprecated in favour of xref:CLI/starkli.adoc[Starkli CLI].
> ```

Maybe it's best to write "deprecates soon", since our guides still using the old CLI. We'll write deprecated once we'll update the guides in the docs.

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/696)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @EvyatarO)

___
*[`components/Starknet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 21 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/696#-N_iVQGT9bKQ_mUM520P:-N_mpKCn34QijtteiPKV:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/74355f30a05f89eb6e90f67d1732ad209af3f1f3/components/Starknet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L21)):*
<details><summary><i>Previously, EvyatarO (Evyatar) wrote…</i></summary><blockquote>

Maybe it's best to write "deprecates soon", since our guides still using the old CLI. We'll write deprecated once we'll update the guides in the docs.
</blockquote></details>

Done.
___
*[`components/Starknet/modules/tools/pages/CLI/commands.adoc` line 6 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/696#-N_iV1IbE997JHuZzlok:-N_mpPJD4X5GHhF5uj41:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/74355f30a05f89eb6e90f67d1732ad209af3f1f3/components/Starknet/modules/tools/pages/CLI/commands.adoc#L6)):*
<details><summary><i>Previously, EvyatarO (Evyatar) wrote…</i></summary><blockquote>

Maybe it's best to write "deprecates soon", since our guides still using the old CLI. We'll write deprecated once we'll update the guides in the docs.
</blockquote></details>

Done.

**Review by EvyatarO — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/696)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Review by EvyatarO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/696#-:-N_s7_HLDrrgReQXjJ5j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Review by stoobie — COMMENTED** [review]
@JameStark I made several comments, but it looks like I forgot to press the **Submit review** button.

**Pull request merged**
