### PR TITLE
Update transaction structure

### PR DESCRIPTION
**Pull request by JameStark**
### Description of the Changes

Update transaction structure

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-294/documentation/

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/294)

### CODE REVIEW

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/294)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/294)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/294)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/294)* status: all files reviewed, 1 unresolved discussion (waiting on @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 209 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/294#-NPN5kZ16PTVt7CFb-7R:-NPN5kZ2BHWyClYFVulm:b-dzjer4) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ad34a11e679d5d0c03599f809c2063df88d39ee5/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L209)):*
> ```AsciiDoc
> * stem:[$h$] is the xref:../Hashing/hash-functions.adoc#pedersen-hash[Pedersen] hash
> 
> === Calculating the hash of a v0 declare transaction
> ```

The hash calculation of declare v0 is different, why remove?

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/294)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 209 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/294#-NPN5kZ16PTVt7CFb-7R:-NPR9Glz07BkXlxd0Syq:b-wydlog) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ad34a11e679d5d0c03599f809c2063df88d39ee5/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L209)):*
>  of declare v0 is differe
I think I was trying to consolidate a bit b ut have reverted based on this (done)

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/294)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/294)* status: all files reviewed, 1 unresolved discussion (waiting on @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 178 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/294#-NPRGRKS1DxSqo6DJyuW:-NPRGRKS1DxSqo6DJyuX:b75rq91) ([raw file](https://github.com/starknet-io/starknet-docs/blob/d23c6a5f7f59bf65b6782727687111cf06295c13/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L178)):*
> ```AsciiDoc
> \end{aligned}
> ++++
> ```

Let's add another where:  ... section here like the other types, with the changes:
- h is the Poseidon hash function (link to poseidon array hashing)
- in the class hash link, link specifically to the hash of a Cairo 1 class
- `compiled_class_hash` is the hash of the (compiled class)[link to what to expect under upcoming] generated by the Sierra-->Casm compiler which is currently used in Starknet 

We need another page with Sierra/compilation/... info, otherwise we keep linking to this one paragraph in the upcoming version doc. Will try to add today and then we can change the link.

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/294)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 178 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/294#-NPRGRKS1DxSqo6DJyuW:-NPRPvPY-k4AEnZRcCd1:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/d23c6a5f7f59bf65b6782727687111cf06295c13/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L178)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Let's add another where:  ... section here like the other types, with the changes:
- h is the Poseidon hash function (link to poseidon array hashing)
- in the class hash link, link specifically to the hash of a Cairo 1 class
- `compiled_class_hash` is the hash of the (compiled class)[link to what to expect under upcoming] generated by the Sierra-->Casm compiler which is currently used in Starknet 

We need another page with Sierra/compilation/... info, otherwise we keep linking to this one paragraph in the upcoming version doc. Will try to add today and then we can change the link.
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/294)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/294#-:-NPSgAPz-wB_c8UnjqL7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @JameStark)

**Pull request merged**
