### PR TITLE
Update api-services.adoc

### PR DESCRIPTION
**Pull request by JoGetBlock**
Add GetBlock to the list of RPC providers as a relevant active service

### Description of the Changes

Add GetBlock as an additional RPC Provider to the list

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.
https://github.com/JoGetBlock/starknet-docs/tree/patch-1

### Check List

- [x] Changes have been done against master branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1038)

### CODE REVIEW

**Comment by JoGetBlock** [comment]
Please review this PR

**Comment by odednaor** [comment]
Checking

**Comment by odednaor** [comment]
@JoGetBlock Please contact me at `oded@starkware.co`.

**Review by odednaor — APPROVED** [review]
lgtm

**Pull request merged**
