### PR TITLE
feat: Add style guide and more details for contributing.

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

This PR adds a style guide and more details to the contribution guide. Content is based on the [OpenShift docs repo](https://github.com/openshift/openshift-docs).

This content is only viewable in this repo, it is not published on docs.starknet.io or anywhere else.

### PR Preview URL

There is no Antora preview for this content. Ignore the preview that is generated for this PR.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/519)

### CODE REVIEW

**Review by JameStark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/519)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @stoobie)

___
*[`contributing_to_docs/doc_guidelines.adoc` line 29 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/519#-N_4OGSy-uUptun4eTBH:-N_4OGSy-uUptun4eTBI:b-b2zm3m) ([raw file](https://github.com/starknet-io/starknet-docs/blob/24632d607bd827c119810434132c1716b38fec10/contributing_to_docs/doc_guidelines.adoc#L29)):*
> ```AsciiDoc
> . xref:starknet_docs_style_guide.adoc[_Starknet documentation style guide_] Reference this guide first. It provides guidance that is specific to Starknet documentation.
> . link:https://redhat-documentation.github.io/supplementary-style-guide[_Red Hat supplementary style guide for product documentation_]. This guide overrides certain guidance from the _Google developer documentation style guide_.
> . link:https://developers.google.com/style[_Google developer documentation style guide_]
> ```

This order differs from https://github.com/starknet-io/starknet-docs/blob/add_style_guide/contributing_to_docs/starknet_docs_style_guide.adoc which states that 'the primary source of style guidance for Starknet documentation.'



_Code quote:_
```AsciiDoc
. link:https://redhat-documentation.github.io/supplementary-style-guide[_Red Hat supplementary style guide for product documentation_]. This guide overrides certain guidance from the _Google developer documentation style guide_.
. link:https://developers.google.com/style[_Google developer documentation style guide_]
```

**Review by JameStark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/519)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @stoobie)

___
*[`README.adoc` line 39 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/519#-N_8Dy143B8jIzciPOl6:-N_8Dy143B8jIzciPOl7:b-w0tywu) ([raw file](https://github.com/starknet-io/starknet-docs/blob/24632d607bd827c119810434132c1716b38fec10/README.adoc#L39)):*
> ```AsciiDoc
> *What happens when you submit a PR?*
> 
> When you submit a PR, the https://github.com/orgs/openshift/teams/team-documentation[Starknet Docs team] reviews the PR and arranges further technical reviews as necessary. If the PR requires changes, the reviewers add comments in the PR. We might request that you make the changes, or let you know that we incorporated your content in a different PR. Occasionally, we might add commits to the original PR directly. When the PR has been reviewed and all updates are complete, the documentation team merges the PR and applies it to the valid version(s).
> ```

Should this link to Starknet?
___
*[`contributing_to_docs/contributing.adoc` line 20 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/519#-N_8E2Tp-BTOiiMlf8ZC:-N_8E2Tp-BTOiiMlf8ZD:b-w0tywu) ([raw file](https://github.com/starknet-io/starknet-docs/blob/24632d607bd827c119810434132c1716b38fec10/contributing_to_docs/contributing.adoc#L20)):*
> ```AsciiDoc
> *What happens when you submit a PR?*
> 
> When you submit a PR, the https://github.com/orgs/openshift/teams/team-documentation[Starknet Docs team] reviews the PR and arranges further technical reviews as necessary. If the PR requires changes, the reviewers add comments in the PR. We might request that you make the changes, or let you know that we incorporated your content in a different PR. Occasionally, we might add commits to the original PR directly. When the PR has been reviewed and all updates are complete, the documentation team merges the PR and applies it to the valid version(s).
> ```

Should this link to Starknet?
___
*[`contributing_to_docs/doc_guidelines.adoc` line 704 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/519#-N_8EJ4FDaP1cu2wSHgM:-N_8EJ4FDaP1cu2wSHgN:b-gpdl62) ([raw file](https://github.com/starknet-io/starknet-docs/blob/24632d607bd827c119810434132c1716b38fec10/contributing_to_docs/doc_guidelines.adoc#L704)):*
> ```AsciiDoc
> +
> ....
> Create a secret that contains the certificate and key in the `openshift-config` namespace:
> ```

Starknet?

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/519)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @JameStark)

___
*[`README.adoc` line 39 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/519#-N_8Dy143B8jIzciPOl6:-N_8U2CcCwEEQF6CmxiL:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/24632d607bd827c119810434132c1716b38fec10/README.adoc#L39)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Should this link to Starknet?
</blockquote></details>

Done.
___
*[`contributing_to_docs/doc_guidelines.adoc` line 29 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/519#-N_4OGSy-uUptun4eTBH:-N_8_Qk241clTGHBEOus:bw5seat) ([raw file](https://github.com/starknet-io/starknet-docs/blob/24632d607bd827c119810434132c1716b38fec10/contributing_to_docs/doc_guidelines.adoc#L29)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

This order differs from https://github.com/starknet-io/starknet-docs/blob/add_style_guide/contributing_to_docs/starknet_docs_style_guide.adoc which states that 'the primary source of style guidance for Starknet documentation.'
</blockquote></details>

Well, this section talks about in what order ot use the guides. The section your quoting just names the guides. On that same page that you're quoting from, the next section provides the same order.
___
*[`contributing_to_docs/doc_guidelines.adoc` line 704 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/519#-N_8EJ4FDaP1cu2wSHgM:-N_8aJRX6pI28Sl5jw7b:bss4a2b) ([raw file](https://github.com/starknet-io/starknet-docs/blob/24632d607bd827c119810434132c1716b38fec10/contributing_to_docs/doc_guidelines.adoc#L704)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Starknet?
</blockquote></details>

Removed.
___
*[`contributing_to_docs/contributing.adoc` line 20 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/519#-N_8E2Tp-BTOiiMlf8ZC:-N_8UMV5277Cwl_RFio_:b-jq816w) ([raw file](https://github.com/starknet-io/starknet-docs/blob/24632d607bd827c119810434132c1716b38fec10/contributing_to_docs/contributing.adoc#L20)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Should this link to Starknet?
</blockquote></details>

I deleted this file and moved any remaining content to doc_guidelines.adoc.

**Review by JameStark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/519#-:-N_8kcAN-nU9DEArstlV:bnfp4nl)* status: 0 of 7 files reviewed, all discussions resolved

**Pull request merged**
