### PR TITLE
Update class hash

### PR DESCRIPTION
**Pull request by JameStark**
### Description of the Changes

Change contract hash to class hash

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-293/documentation/

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/293)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/293)* status: all files reviewed, 3 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc` line 45 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/293#-NOp16RUBNWTfN2l4BLV:-NOp16RUBNWTfN2l4BLW:b-iui250) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b17674a6a30eb192d1fe6d915bd66339e45a702/components/StarkNet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc#L45)):*
> ```AsciiDoc
> 
> [horizontal,labelwidth=35]
> Sierra version:: the Sierra version in which the class is written
> ```

Rename to contract_class_version



_Code quote:_
```AsciiDoc
Sierra version
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc` line 45 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/293#-NOp19Ca4Q_N0K1d4Bkc:-NOp19Ca4Q_N0K1d4Bkd:b1ubz4z) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b17674a6a30eb192d1fe6d915bd66339e45a702/components/StarkNet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc#L45)):*
> ```AsciiDoc
> 
> [horizontal,labelwidth=35]
> Sierra version:: the Sierra version in which the class is written
> ```

Change the description to:

The version of the contract class object. Currently the Starknet OS supports version 1 



_Code quote:_
```AsciiDoc
the Sierra version in which the class is written
```
___
*[`components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc` line 93 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/293#-NOp1_pn4KZyajeM8Vgf:-NOp1_pn4KZyajeM8Vgg:bpmobfa) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b17674a6a30eb192d1fe6d915bd66339e45a702/components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc#L93)):*
> ```AsciiDoc
> New class hash computation will migrate from Pedersen to Poseidon hash functions in this version.
> 
> New class hash computation will migrate from Pedersen to Poseidon hash functions in this version.
> ```

Looks like this line exists twice now

I think that I have an open task for the Poseidon changes, let's remove this from here because it's a bit more delicate (old classes still use Pedersen)

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/293)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc` line 45 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/293#-NOp16RUBNWTfN2l4BLV:-NOsBT_k9tK9-lpIpmaq:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b17674a6a30eb192d1fe6d915bd66339e45a702/components/StarkNet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc#L45)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Rename to contract_class_version
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc` line 45 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/293#-NOp19Ca4Q_N0K1d4Bkc:-NOsBbME4mKLmpI8VoA2:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b17674a6a30eb192d1fe6d915bd66339e45a702/components/StarkNet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc#L45)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Change the description to:

The version of the contract class object. Currently the Starknet OS supports version 1 
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc` line 93 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/293#-NOp1_pn4KZyajeM8Vgf:-NOsBrug4_ZDFimYYl_9:b-ulm1ow) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1b17674a6a30eb192d1fe6d915bd66339e45a702/components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc#L93)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Looks like this line exists twice now

I think that I have an open task for the Poseidon changes, let's remove this from here because it's a bit more delicate (old classes still use Pedersen)
</blockquote></details>

My mistake, merge conflict error - done



_Code quote:_
```AsciiDoc
utation will migrate from Pedersen to Poseidon hash functions in this 
```

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/293)* status: all files reviewed, 2 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc` line 91 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/293#-NOsJDoZ35Z7sP65CdwO:-NOsJDoZ35Z7sP65CdwP:b-k1xw2) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f51aeb6791d73b872e7a82bbf319bbb7838c994d/components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc#L91)):*
> ```AsciiDoc
> * `h` is the link:Poseidon hash function
> 
> New class hash computation will migrate from Pedersen to Poseidon hash functions in this version.
> ```

This shouldn't be under state commitment; let's remove this from here



_Code quote:_
```AsciiDoc
New class hash computation will migrate from Pedersen to Poseidon hash functions in this version.
```

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/293)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc` line 91 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/293#-NOsJDoZ35Z7sP65CdwO:-NOsKo5DDTnTDsXXh3Xr:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f51aeb6791d73b872e7a82bbf319bbb7838c994d/components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc#L91)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

This shouldn't be under state commitment; let's remove this from here
</blockquote></details>

Done.

**Review by ArielElp — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/293#-:-NOsT4nO1mKqlDwR515D:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Pull request merged**
