### PR TITLE
docs: Remove info on removing a token

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

Remove info on removing a token.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [x] Changes have been done against main branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1079)

### CODE REVIEW

**Review by natan-granit — COMMENTED** [review]
LGTM

**Comment by stoobie** [comment]
> its reference page is 404 because can't find the repo `https://github.com/starkware-libs/starkgate`.

@xiaolou86 Thanks for pointing this out!

**Comment by xiaolou86** [comment]
@stoobie I will try to fix it when I have time.

**Comment by stoobie** [comment]
> @stoobie I will try to fix it when I have time.

@xiaolou86 I think that the fix is just to comment out those links. I'll take care of it.

**Comment by xiaolou86** [comment]
> > @stoobie I will try to fix it when I have time.
> 
> @xiaolou86 I think that the fix is just to comment out those links. I'll take care of it.

@stoobie I have done and please help me to review #1081

**Pull request merged**
