### PR TITLE
feat: adding contributors

### LINKED ISSUE #1042: *Seeking Contribution* Add list of contributors
Add a list of contributors. Ideally, this would be automatically updated. If you know how to do this, such a contribution would be very much appreciated!

Ideally, you should be able to see a list of contributors on each published page, like the **See contributors** button in the developer documentation on  Ethereum.org:
image

  **TIP**
  From @omahs: 
  > For the Contributors list, this tool is used on many repos: https://allcontributors.org/

This contribution is eligible for funding via OnlyDust. If you are interested in taking on this PR, please leave a comment to let me know.

### PR DESCRIPTION
**Pull request by xiaolou86**
### Description of the Changes

Resolves #1042. Uses the changes from https://github.com/starknet-io/starknet-docs-antora-ui/pull/39.

Adding contributors

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [x] Changes have been done against main branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1268)

### CODE REVIEW

**Comment by stoobie** [comment]
@xiaolou86 I just took a quick look, at a glance it looks pretty good! I need to review it more in-depth next week.

**Comment by stoobie** [comment]
For transparency, I'm copying the question I asked the contributor in https://github.com/starknet-io/starknet-docs-antora-ui/pull/39:
> Can you tell me the source of your code? Did you write it yourself or is from another open source project? Before we can use it, I need to make sure we're allowed to use it.

**Comment by xiaolou86** [comment]
I have updated some code, need to generate preview again.

**Comment by stoobie** [comment]
No more need for this PR. Changes are merged from the starknet-docs-antora-ui project PR#39.

**Pull request closed without merging**
