### PR TITLE
docs: Clarify transaction-life-cycle.adoc

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

Updated the section on the Transaction receipt, using an example from the JSON RPC instead of the Feeder Gateway.

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-903/documentation/architecture_and_concepts/Network_Architecture/transaction-life-cycle/

### Check List

- [x] Changes have been done against dev branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/903)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/903)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @LandauRaz and @stoobie)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 17 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwglDhC0AVMauQ4e7y:-NhwglDhC0AVMauQ4e7z:byjp4hq) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L17)):*
> ```AsciiDoc
> The mempool performs a preliminary validation on the transaction. If the transaction is invalid, it does not proceed.
> 
> . *Sequencer validation:* The sequencer performs validation on the transaction before executing it to ensure that the transaction is still valid. If the transaction is invalid, it does not proceed.
> ```

This sounds weird if you come from Ethereum. Somehow in the beginning we need to explain that validation in this context is analogous to Ethereum's signature checking (running the account's validate + various checks such as making sure the current balance exceeds the max_fee)
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 19 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwhFOz1eVtb5Osow9U:-NhwhFOz1eVtb5Osow9V:buly0z7) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L19)):*
> ```AsciiDoc
> . *Sequencer validation:* The sequencer performs validation on the transaction before executing it to ensure that the transaction is still valid. If the transaction is invalid, it does not proceed.
> 
> . *Execution:* The sequencer operation sequentially applies all validated transactions to the state. If a transaction fails during execution, it is included in the block with the status `REVERTED`.
> ```

"validated transactions" sounds weird, as if you already executed them, I suggest removing
(the sequencer applies the transactions on the current state)
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 23 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwhXIS1wB_R2D0JuLu:-NhwhXIS1wB_R2D0JuLv:b-16fhz3) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L23)):*
> ```AsciiDoc
> . *Proof generation:* The Prover executes the operating system on the new block, computes the proof, and transmits it to L1.
> 
> #What about verification? Is that not considered part of the transaction lifecycle?#
> ```

transmits the proof to L1 = verification
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 41 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwhlNv9p4P_cSTKm0i:-NhwhlNv9p4P_cSTKm0j:bag0pd7) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L41)):*
> ```AsciiDoc
> .4+|*Finality* |`NOT_RECEIVED` |The transaction is not yet known to the sequencer.
> |`RECEIVED` |The transaction was received by the mempool. The transaction now either executes successfully, is rejected, or reverted.
> |`ACCEPTED_ON_L2` |The transaction passed validation and entered an actual created block on L2.
> ```

was executed
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 54 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwhuMg65nLkS933gCk:-NhwhuMg65nLkS933gCl:b-miat2c) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L54)):*
> ```AsciiDoc
> When a transaction is marked as `REVERTED`, the following state implications occur #Do these occur in order? If so, then this should be a numbered list#:
> [horizontal,labelwidth="20",role="stripes-odd"]
> Nonce increases:: The nonce value for the account of the failed transaction iterates despite the failure.
> ```

suggesting: the nonce of the corresponding account is bumped
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 58 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-Nhwi6WTAswBPaaaPjFH:-Nhwi6WTAswBPaaaPjFI:b91bb5t) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L58)):*
> ```AsciiDoc
> Fee charge:: A fee is charged for the execution of the transaction up to the point of failure.
> 
> Partial reversion:: All changes that occurred during the `validate` stage are not reverted. However, all changes that occurred during the `execute` stage are reverted, including no messages to L1 or events.
> ```

Add: events may still be emitted from the validate phase or the fee transfer phase (a `Transfer` event from the account to the sequencer)
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 62 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwiSGn79G2TpOi-IAe:-NhwiSGn79G2TpOi-IAf:b-113sba) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L62)):*
> ```AsciiDoc
> Fee calculation:: The fee charged for `REVERTED` transactions is calculated as follows:
> +
> #Is this an actual function or pseudo code? If an actual function, then what language is it and where is it defined? If it's pseudo code, then we should probably make it stem formatting.#
> ```

pseudo code
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 78 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwijDg4ANU2P544mMd:-NhwijDg4ANU2P544mMe:bh1zjk) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L78)):*
> ```AsciiDoc
> 
> * Basic transaction details, including the block identifier and the index within the block.
> * A summary of the execution resources used by the transaction.#Where is this in the example below?#
> ```

It's not there (mistake probably). You need a receipt example from some current node / api provider.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 79 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwiyD59eQLNqokYcqs:-NhwiyD59eQLNqokYcqt:bnj7hl0) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L79)):*
> ```AsciiDoc
> * Basic transaction details, including the block identifier and the index within the block.
> * A summary of the execution resources used by the transaction.#Where is this in the example below?#
> * The events emitted. #Where are the events emitted in the example below?#
> ```

same as above
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 81 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-Nhwj0237bnIJvpHELEb:-Nhwj0240NfxujqVquHG:b-sx00c1) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L81)):*
> ```AsciiDoc
> * The events emitted. #Where are the events emitted in the example below?#
> * A list of messages sent to L1. #In the example, what is the difference between this item and the next (consumed L1 message)?#
> * A consumed L1 message, if the transaction invokes an L1 handler. #Is this the calldata in the examle below?#
> ```

No, same as above

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/903)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @ArielElp and @LandauRaz)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 17 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwglDhC0AVMauQ4e7y:-NijSz8R3n4DIoUTxQ8e:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L17)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

This sounds weird if you come from Ethereum. Somehow in the beginning we need to explain that validation in this context is analogous to Ethereum's signature checking (running the account's validate + various checks such as making sure the current balance exceeds the max_fee)
</blockquote></details>

Done
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 19 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwhFOz1eVtb5Osow9U:-NijTMMO2tYZeNOD4zJR:bvg5nk5) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L19)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

"validated transactions" sounds weird, as if you already executed them, I suggest removing
(the sequencer applies the transactions on the current state)
</blockquote></details>

Fixed, but with different wording. I still want to make it clear that the transactions that are executed are only those that passed the previous step. PTAL.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 23 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwhXIS1wB_R2D0JuLu:-NijVPPd-rBYdWYzDPKs:b-qo5v13) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L23)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

transmits the proof to L1 = verification
</blockquote></details>

I added some text to clarify further. PTAL.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 54 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwhuMg65nLkS933gCk:-Ni-km6c9GLM27VOHR2m:boknzmd) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L54)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

suggesting: the nonce of the corresponding account is bumped
</blockquote></details>

What does "bumped" mean?

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/903)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @ArielElp and @LandauRaz)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 41 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwhlNv9p4P_cSTKm0i:-NinIzx3BDYdIAJi4Gb9:bd61lpy) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L41)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

was executed
</blockquote></details>

Can you please be clear about what you're suggesting should change? You can highlight the text you want to change and then your comment will show me what I should remove and what the replacement text should be.

Do you mean that instead of saying: `The transaction passed validation and entered an actual created block on L2.`
It should say this: `The transaction was executed and entered an actual created block on L2.`
?
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 52 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NinKRBy1HwcSHMMievE:-NinKRBy1HwcSHMMievF:b-u6jmb) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L52)):*
> ```AsciiDoc
> == State implications of a reverted transaction
> 
> When a transaction is marked as `REVERTED`, the following state implications occur #Do these occur in order? If so, then this should be a numbered list#:
> ```

@ArielElp Please answer this question.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 54 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwhuMg65nLkS933gCk:-NinJdTh50mU2LcyOKAk:bndwxwy) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L54)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

What does "bumped" mean?
</blockquote></details>

Do you mean that if the nonce was 1, it is now 2?
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 58 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-Nhwi6WTAswBPaaaPjFH:-NinKakD6BxJZncS00tW:b-unjb0a) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L58)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Add: events may still be emitted from the validate phase or the fee transfer phase (a `Transfer` event from the account to the sequencer)
</blockquote></details>

DONE. PTAL.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 78 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwijDg4ANU2P544mMd:-NinM6IO7qSKm5AvfvVW:b3vmqnq) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L78)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

It's not there (mistake probably). You need a receipt example from some current node / api provider.
</blockquote></details>

Can you supply this example or point me in the right direction?

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/903)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @ArielElp and @odednaor)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 79 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-NhwiyD59eQLNqokYcqs:-NjGyv-X7zu0FE3fMCuE:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L79)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc` line 81 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/903#-Nhwj0237bnIJvpHELEb:-NjmDoAz3aO4jUEzI5dZ:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/32c275dc92997e2206755ffaa3ec54778a9bba36/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc#L81)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

No, same as above
</blockquote></details>

Done

**Review by stoobie — COMMENTED** [review]
> Dismissed @ArielElp from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/903)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @ArielElp and @odednaor)

**Pull request merged**
