### PR TITLE
chore: add codespell linter workflow for CI (was #953)

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

* fix: several typos in the documentation

* feat: add codespell linter workflow for CI

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [x] Changes have been done against master branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1007)

### CODE REVIEW

**Comment by stoobie** [comment]
@xiaolou86:
- Is there a way to have this fun only on .adoc files?
- Shouldn't this run before building the HTML?

**Comment by xiaolou86** [comment]
@stoobie I looked into the `typos`'s introduction just now, and have found the solution. 

But how to commit to master branch? Do I create a PR to commit to xiaolou86dev branch?

**Comment by xiaolou86** [comment]
> * Shouldn't this run before building the HTML?

I found  the `deploy-review` job was depended on `Test deploy` job, and `typos` job is independed with them.  If we want to run `typos` job firstly, we can add dependency relationship between them.

**Comment by stoobie** [comment]
> @stoobie I looked into the `typos`'s introduction just now, and have found the solution.
> 
> But how to commit to master branch? Do I create a PR to commit to xiaolou86dev branch?

@xiaolou86 I just sent you an invite to be a collaborator on the Starknet docs. You can clone the repo directly instead of from a fork. The preview should work that way. I still need to approve before merging to master.

**Comment by xiaolou86** [comment]
@stoobie awesome! It's my pleasure to be a collaborator here. Thank you very much. It's too late today, I will try to do it tomorrow.

**Comment by xiaolou86** [comment]
hello @stoobie , I add commits, and do I push to xiaolou86dev branch in this repo directly?

**Comment by stoobie** [comment]
> > * Do you know why the job is failing?
> 
> There are two warnings in the file CHANGELOG.md reported by `typos`
> 
> Warning: "ba" should be "by" or "be". Warning: "inital" should be "initial".
> 
> I think we can ignore the CHANGELOG.md by add blacklist.

Agreed. I saw the same thing on the Cairo Book.

**Comment by stoobie** [comment]
> hello @stoobie , I add commits, and do I push to xiaolou86dev branch in this repo directly?

Yes.

**Comment by stoobie** [comment]
> @stoobie please help to review

OK, will take a look when I have a chance. Thanks!

**Comment by stoobie** [comment]
@xiaolou86 I merged this. Thanks for adding it! However, now when it comes across a typo in a PR, instead of just fixing it, it throws an error that stops the rest of the workflows.

It finds a typo, which throws an error that kills subsequent workflows. I manually fix the typo and then commit the change. Then, if it finds another typo, again, it throws an error that kills subsequent workflows, and the process repeats until there aren't any more typos.

Can you think of a way to make this more efficient? And I'm not sure why it didn't just fix the typos itself.

**Pull request merged**
