### PR TITLE
Add feeless L1 messaging to deprecated features page

### PR DESCRIPTION
**Pull request by JameStark**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/175)

### CODE REVIEW

**Review by JameStark — COMMENTED** [review]
@bbrandtom @arielelp Any suggestions on wording here? Do we have any info we can share on how the fee will be calculated?

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/175#-:-NKX6cuV6KjBeE3fGmGC:bec8893)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @bbrandtom)

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/175)* status: all files reviewed, 2 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 20 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/175#-NKhSdwn9U9kB8EKHUz0:-NKhSdwo2ZNfmJDncjzW:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/a9067639af84bbfb82f1bba0aef3303a842bc7a2/components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L20)):*
> ```AsciiDoc
> |Name|Description
> 
> |L2 -> L1 messaging |Previously, sending a message from L2 to L1 was feeless.
> ```





_Suggestion:_
```AsciiDoc
L1 to L2
```
___
*[`components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 22 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/175#-NKhSh8K4T-_GUcnnOlp:-NKhSh8LC-5qqBcUpxDb:b22dzbi) ([raw file](https://github.com/starknet-io/starknet-docs/blob/a9067639af84bbfb82f1bba0aef3303a842bc7a2/components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L22)):*
> ```AsciiDoc
> |L2 -> L1 messaging |Previously, sending a message from L2 to L1 was feeless.
> 
> From StarkNet version 0.11.0 a fee for this messaging mechanism will be introduced.
> ```

The fee mechanism was already introduced on v0.10.0.
From v0.11.0, it will be enforced and the ability to pay without fees will be removed.



_Code quote:_
```AsciiDoc
fee for this messaging mechanism will be introduced.
```

**Review by bbrandtom — COMMENTED** [review]
You can link to the place in the docs - https://docs.starknet.io/documentation/architecture_and_concepts/L1-L2_Communication/messaging-mechanism/#l1-l2_message_fees

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/175#-:-NKnYt77B5oytFm4S_li:b-o09tvx)* status: all files reviewed, 2 unresolved discussions (waiting on @JameStark)

**Review by bbrandtom — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/175)* status: all files reviewed, 1 unresolved discussion (waiting on @JameStark)

___
*[`components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc` line 22 at r4](https://reviewable.io/reviews/starknet-io/starknet-docs/175#-NKquVOQAEkJ1T8Jx3GU:-NKquVOQAEkJ1T8Jx3GV:bmqdghm) ([raw file](https://github.com/starknet-io/starknet-docs/blob/15dad8218fe9aaed93db49c6cf5cbf21cf13d3d5/components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc#L22)):*
> ```AsciiDoc
> |L2 -> L1 messaging |Previously, sending a message from L2 to L1 had an optional fee associated.
> 
> From StarkNet version 0.11.0, the fee mechanism will be enforced and the ability to pay without fees will be removed.
> ```

Do we want to link to the section in the docs that explains it? https://docs.starknet.io/documentation/architecture_and_concepts/L1-L2_Communication/messaging-mechanism/#l1-l2_message_fees

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/175)* status: all files reviewed, 1 unresolved discussion (waiting on @JameStark)

**Review by JameStark — COMMENTED** [review]
Done, let me know if I can go ahead and deploy this change

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/175#-:-NKr79cM-ZNEV4GrnfvK:b-calphu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Pull request merged**
