### PR TITLE
James: Remove constructor calldata references

### PR DESCRIPTION
**Pull request by JameStark**
We used to send the constructor calldata to L1. This was a mistake as it isn't needed to reconstruct the current state from L1 information; therefore, we stopped sending it a few months ago. This is not updated in the docs in two places:

on chain data format - https://docs.starknet.io/documentation/develop/Data_Availability/on-chain-data/#format, we need to remove len(constructor_call_data) and constructor_call_data from the list and edit the example itself.
fees: remove the part about constructor arguments from the final formula https://docs.starknet.io/documentation/develop/Fees/fee-mechanism/#overall_fee (verify that this is not mentioned elsewhere there)

Preview:
https://starknet-io.github.io/starknet-docs/pr-121/documentation/

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/121)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/121)* status: all files reviewed, 5 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/develop/pages/Data_Availability/on-chain-data.adoc` line 77 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/121#-NH4jxi639kNAVudZKGT:-NH4jxi639kNAVudZKGU:b-kfib60) ([raw file](https://github.com/starknet-io/starknet-docs/blob/0f513cb04c4b2fc94ef0c63575957a51b5d04d97/components/StarkNet/modules/develop/pages/Data_Availability/on-chain-data.adoc#L77)):*
> ```AsciiDoc
> ----
> 
> * The first element, 5, is the number of cells that encode contracts deployment.
> ```

Change to 2



_Code quote:_
```AsciiDoc
The first element, 5
```
___
*[`components/StarkNet/modules/develop/pages/Data_Availability/on-chain-data.adoc` line 78 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/121#-NH4k4G29LiBJDsTQshf:-NH4k4G29LiBJDsTQshg:b2nhpmv) ([raw file](https://github.com/starknet-io/starknet-docs/blob/0f513cb04c4b2fc94ef0c63575957a51b5d04d97/components/StarkNet/modules/develop/pages/Data_Availability/on-chain-data.adoc#L78)):*
> ```AsciiDoc
> 
> * The first element, 5, is the number of cells that encode contracts deployment.
> * The next five elements describe a single contract deployment with the following parameters:
> ```

Two



_Code quote:_
```AsciiDoc
five
```
___
*[`components/StarkNet/modules/develop/pages/Data_Availability/on-chain-data.adoc` line 91 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/121#-NH4k9sW0xsWMWmpppnD:-NH4k9sW0xsWMWmpppnE:b22quet) ([raw file](https://github.com/starknet-io/starknet-docs/blob/0f513cb04c4b2fc94ef0c63575957a51b5d04d97/components/StarkNet/modules/develop/pages/Data_Availability/on-chain-data.adoc#L91)):*
> ```AsciiDoc
> ----
> 
>  ** Two constructor arguments (indicated by the cell at index 3):
> ```

Remove this



_Code quote:_
```AsciiDoc
 ** Two constructor arguments (indicated by the cell at index 3):
+
----
955723665991825982403667749532843665052270105995360175183368988948217233556
----
+
----
2439272289032330041885427773916021390926903450917097317807468082958581062272
----
```
___
*[`components/StarkNet/modules/develop/pages/Fees/fee-mechanism.adoc` line 152 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/121#-NH4kT0y2zpgv5w2A8vw:-NH4kT0y2zpgv5w2A8vx:b-un4bmb) ([raw file](https://github.com/starknet-io/starknet-docs/blob/8c45449ecbd75139dd40fc19e9b5e3b5ae89ce37/components/StarkNet/modules/develop/pages/Fees/fee-mechanism.adoc#L152)):*
> ```AsciiDoc
> [stem]
> ++++
> \text{gas_price}\cdot c_w\cdot(3+\text{# of constructor arguments})
> ```

Change to:
\text{gas_price}\cdot 2 c_w



_Code quote:_
```AsciiDoc
\text{gas_price}\cdot c_w\cdot(3+\text{# of constructor arguments})
```
___
*[`components/StarkNet/modules/develop/pages/Fees/fee-mechanism.adoc` line 163 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/121#-NH4kk95A9hw9k5b0Xi9:-NH4kk95A9hw9k5b0XiA:b-3wf8fy) ([raw file](https://github.com/starknet-io/starknet-docs/blob/8c45449ecbd75139dd40fc19e9b5e3b5ae89ce37/components/StarkNet/modules/develop/pages/Fees/fee-mechanism.adoc#L163)):*
> ```AsciiDoc
> * stem:[$m$] unique key updates
> * stem:[$t$] messages with payload sizes stem:[$q_1,...,q_t$]
> * stem:[$\ell$] deployments with number of constructor arguments stem:[$c_1,...,c_\ell$]
> ```

We still need an explanation on what L (\ell) is as it appears in the formula
Keep the following:
 * stem:[$\ell$] number of contract deployments

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/121)* status: all files reviewed, 5 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/develop/pages/Data_Availability/on-chain-data.adoc` line 77 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/121#-NH4jxi639kNAVudZKGT:-NH4lS-T1jahYvTVPgaP:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/0f513cb04c4b2fc94ef0c63575957a51b5d04d97/components/StarkNet/modules/develop/pages/Data_Availability/on-chain-data.adoc#L77)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Change to 2
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
he first element, 5, is the number of cells that e
```
___
*[`components/StarkNet/modules/develop/pages/Data_Availability/on-chain-data.adoc` line 78 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/121#-NH4k4G29LiBJDsTQshf:-NH4lX6m8zLR3N1Z33CE:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/0f513cb04c4b2fc94ef0c63575957a51b5d04d97/components/StarkNet/modules/develop/pages/Data_Availability/on-chain-data.adoc#L78)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Two
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
e next five elements describe
```
___
*[`components/StarkNet/modules/develop/pages/Data_Availability/on-chain-data.adoc` line 91 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/121#-NH4k9sW0xsWMWmpppnD:-NH4lgZT4RH2IL6qpe5y:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/0f513cb04c4b2fc94ef0c63575957a51b5d04d97/components/StarkNet/modules/develop/pages/Data_Availability/on-chain-data.adoc#L91)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Remove this
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Fees/fee-mechanism.adoc` line 152 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/121#-NH4kT0y2zpgv5w2A8vw:-NH4m0mNBCmUQbRW9VfK:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/8c45449ecbd75139dd40fc19e9b5e3b5ae89ce37/components/StarkNet/modules/develop/pages/Fees/fee-mechanism.adoc#L152)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Change to:
\text{gas_price}\cdot 2 c_w
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Fees/fee-mechanism.adoc` line 163 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/121#-NH4kk95A9hw9k5b0Xi9:-NH4mHtVBi6n4r5rIG8w:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/8c45449ecbd75139dd40fc19e9b5e3b5ae89ce37/components/StarkNet/modules/develop/pages/Fees/fee-mechanism.adoc#L163)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

We still need an explanation on what L (\ell) is as it appears in the formula
Keep the following:
 * stem:[$\ell$] number of contract deployments
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/121)* status: all files reviewed, 5 unresolved discussions (waiting on @ArielElp)

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/121)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`components/StarkNet/modules/develop/pages/Fees/fee-mechanism.adoc` line 163 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/121#-NH4kk95A9hw9k5b0Xi9:-NH50A5v9jInPRTbD9-2:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/8c45449ecbd75139dd40fc19e9b5e3b5ae89ce37/components/StarkNet/modules/develop/pages/Fees/fee-mechanism.adoc#L163)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Actually, just "contract deployments", sorry (for all the above parameters we didn't do "number of")
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/121)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

**Pull request merged**
