### PR TITLE
docs: Add Remix Quick start

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

This rebases main on top of #1210.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [x] Changes have been done against main branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1315)

### CODE REVIEW

**Comment by stoobie** [comment]
@SimplementeCao I'm merging this instead of #1210, as I've taken care of rebasing in this one. I used your commits, so you will still appear as a contributor.

**Comment by stoobie** [comment]
@SimplementeCao  For some reason, I'm not seeing you listed in the list of contributors for this topic. There must be a bug in the code, or maybe it just adds the author of the merged PR, not all contributors to the PR. I suggest that you open a tiny PR for this page with a slight change (even just add an empty line). Hopefully doing that will add you to the list of contributors.

**Comment by SimplementeCao** [comment]
Thank you very much @stoobie, due to health problems I could not continue, I am just starting again. If there is no problem I will do the pr.

**Comment by stoobie** [comment]
Hi @SimplementeCao , the PR is already merged, but you're welcome to take a look and improve it in any way you can.

**Pull request merged**
