### PR TITLE
docs: added solidity verifier

### PR DESCRIPTION
**Pull request by duedme**
### Description of the Changes

This is the addition of the Solidity Verifier documentation to the Network Architecture Section under Architecture and Concepts module.

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-1285/documentation/

### Check List

- [X] Changes have been done against main branch, and PR does not conflict
- [X] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

CC: @omarespejel 

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1285)

### CODE REVIEW

**Comment by stoobie** [comment]
@duedme Thanks for the contribution :)

Is this just a straight copy-paste from the Book? Or did you make any edits?

**Comment by duedme** [comment]
> @duedme Thanks for the contribution :)
> 
> Is this just a straight copy-paste from the Book? Or did you make any edits?

Hi! In this PR and in #1286 I used the book as a foundation. However, I made edits to ensure it aligns with the writing guidelines and style of the project documentation. Please let me know if should make changes or modify content.

**Comment by stoobie** [comment]
I had to do a rebase and I'm making some other edits. I'm using your branch and rebased main on top of it in #1311.

**Comment by stoobie** [comment]
I also added my changed here, because for some reason previews are not being generated from the #1311 or #1314, but it's still not generating here. Can you please try rebasing from main? You'll need to move the topic and images from architecture_and_concepts/ to architecture-and-concepts, and change /Network_Architecture/ to /network-architecture/

**Comment by stoobie** [comment]
#1314 Replaces this.

**Pull request closed without merging**
