### PR TITLE
docs: Add changes for 0.12.1 going live on Mainnet

### PR DESCRIPTION
**Pull request by JameStark**
### Description of the Changes

- Change version notes and upcoming version (for 0.12.2)
- Add Transaction flow updates for 0.12.1

### PR Preview URL
**Version notes:** https://starknet-io.github.io/starknet-docs/pr-703/documentation/starknet_versions/version_notes/

**Upcoming Versions:** https://starknet-io.github.io/starknet-docs/pr-703/documentation/starknet_versions/upcoming_versions/

**Transaction flow:** https://starknet-io.github.io/starknet-docs/pr-703/documentation/architecture_and_concepts/Blocks/transaction-life-cycle/

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/703)

### CODE REVIEW

**Review by EvyatarO — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/703)* status: 0 of 6 files reviewed, 9 unresolved discussions (waiting on @JameStark)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc` line 28 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-NauwkaWAJmPFF3QA0tB:-NauwkaWAJmPFF3QA0tC:b-v841m0) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f8d6ead172597df06a9c604f427b4643e5601a17/components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc#L28)):*
> ```AsciiDoc
> [id="transaction_status"]
> 
> == Transaction status
> ```

We should have two different titles:
finality status (RECEIVED, ACCEPTED_ON_L1/2)
and execution status (REJECTED/REVERTED/SUCCEEDED)



_Code quote:_
```AsciiDoc
== Transaction status
```
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc` line 62 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-NauwZ1j4MWC5_q7GNeM:-NauwZ1j4MWC5_q7GNeN:b-ohmqz1) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f8d6ead172597df06a9c604f427b4643e5601a17/components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc#L62)):*
> ```AsciiDoc
> The transaction passed validation but failed during execution in the sequencer. They will be included in the block with the status `REVERTED`.
> 
> The diagram below illustrates how each transaction status fits into the overall transaction flow:
> ```

I'd move it up, right below 4. Proof generation
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc` line 81 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-Nauw2mc0s4jS-7usZxz:-Nauw2md7M-fqN8uT-Sy:b8qf3m2) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f8d6ead172597df06a9c604f427b4643e5601a17/components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc#L81)):*
> ```AsciiDoc
> [source,bash]
> ----
> fee = Min(max_fee, consumed_resources) * configurable_factor
> ```

We can simply remove it



_Code quote:_
```AsciiDoc
* configurable_factor
```
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc` line 83 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-Nauw-KZ5UVuTvGc3j2t:-Nauw-KZ5UVuTvGc3j2u:b32wof) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f8d6ead172597df06a9c604f427b4643e5601a17/components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc#L83)):*
> ```AsciiDoc
> fee = Min(max_fee, consumed_resources) * configurable_factor
> ----
> where the `configurable_factor` will be 1.
> ```

is



_Code quote:_
```AsciiDoc
will be
```
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc` line 107 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-Nauw6uEBGcS4YcDcFjz:-Nauw6uEBGcS4YcDcFk-:by9bn3z) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f8d6ead172597df06a9c604f427b4643e5601a17/components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc#L107)):*
> ```AsciiDoc
>   "execution_status": "SUCCEEDED",
>   "finality_status": "ACCEPTED_ON_L2",
>   "status": "ACCEPTED_ON_L2",
> ```

Remove this line



_Code quote:_
```AsciiDoc
"status": "ACCEPTED_ON_L2",
```
___
*[`components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc` line 8 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-NauvRdlBecMQjls6aic:-NauvRdlBecMQjls6aid:byzbvpx) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f8d6ead172597df06a9c604f427b4643e5601a17/components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc#L8)):*
> ```AsciiDoc
> 
> ### What to expect
> The focus of Starknet v0.12.2 is to enhance Starknet's reliability and performance.
> ```

WDYT about adding a link to the forum post? I'm not sure if it's good or not.

(I do think we should add this link to the roadmap cards BTW)



_Code quote:_
```AsciiDoc
to enhance Starknet's reliability and performance.
```
___
*[`components/Starknet/modules/starknet_versions/pages/version_notes.adoc` line 14 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-Nauv8kA8x7pd0zNK5Jr:-Nauv8kA8x7pd0zNK5Js:bvcq7yb) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f8d6ead172597df06a9c604f427b4643e5601a17/components/Starknet/modules/starknet_versions/pages/version_notes.adoc#L14)):*
> ```AsciiDoc
> |===
> |*Environment* |*Starknet version*|*Cairo version*
> |Mainnet|0.12.1|2.0.0
> ```

Aren't we usually update the docs when we go live to Testnet?



_Code quote:_
```AsciiDoc
1
```
___
*[`components/Starknet/modules/starknet_versions/pages/version_notes.adoc` line 15 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-NauvErgCiD3-SShc7fR:-NauvErgCiD3-SShc7fS:bskmx43) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f8d6ead172597df06a9c604f427b4643e5601a17/components/Starknet/modules/starknet_versions/pages/version_notes.adoc#L15)):*
> ```AsciiDoc
> |*Environment* |*Starknet version*|*Cairo version*
> |Mainnet|0.12.1|2.0.0
> |Goerli Testnet 1|0.12.1|2.0.0
> ```

2.1.0
In all of them



_Code quote:_
```AsciiDoc
0
```
___
*[`components/Starknet/modules/starknet_versions/pages/version_notes.adoc` line 27 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-Nauv4HHDmGa82PKODQu:-Nauv4HHDmGa82PKODQv:b-vo9f2a) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f8d6ead172597df06a9c604f427b4643e5601a17/components/Starknet/modules/starknet_versions/pages/version_notes.adoc#L27)):*
> ```AsciiDoc
> * Mempool Validation.
> * Inclusion of Failed Transactions.
> * Keccak builtins.
> ```

builtin



_Code quote:_
```AsciiDoc
builtins
```

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/703)* status: 0 of 6 files reviewed, 9 unresolved discussions (waiting on @EvyatarO)

___
*[`components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc` line 8 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-NauvRdlBecMQjls6aic:-NavOxUM4Atqs_W2VRHz:b-t2hiz3) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f8d6ead172597df06a9c604f427b4643e5601a17/components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc#L8)):*
<details><summary><i>Previously, EvyatarO (Evyatar) wrote…</i></summary><blockquote>

WDYT about adding a link to the forum post? I'm not sure if it's good or not.

(I do think we should add this link to the roadmap cards BTW)
</blockquote></details>

I think this would be good (both community link and roadmap cards) as they are both interesting to someone reading this. I am going to incorporate a section here for both in a separate PR.

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 3 files at r4, 1 of 1 files at r5, 1 of 2 files at r6, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/703)* status: all files reviewed, 9 unresolved discussions (waiting on @EvyatarO)

**Review by EvyatarO — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r5, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/703)* status: all files reviewed, 3 unresolved discussions (waiting on @JameStark)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc` line 83 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-Nauw-KZ5UVuTvGc3j2t:-NavQ3QlB-neByZGWSRY:b-fvqey6) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f8d6ead172597df06a9c604f427b4643e5601a17/components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc#L83)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, we can delete this line if we removed the configurable_factor from the equation above.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc` line 47 at r9](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-NavPdVy9af2Ssy3yjCb:-NavPdVz9bDdWnKxgSkV:br4s247) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6fed69d25f9a5a209a94a10203e5e6cab792b0ae/components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc#L47)):*
> ```AsciiDoc
> ==== RECEIVED
> 
> The transaction was received by the mempool. The transaction will now either execute successfully or be rejected.
> ```

It could also be Revert



_Code quote:_
```AsciiDoc
successfully
```
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc` line 57 at r9](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-NavPp_y9gqpxhb4CXcz:-NavPp_y9gqpxhb4CXd-:bf951xa) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6fed69d25f9a5a209a94a10203e5e6cab792b0ae/components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc#L57)):*
> ```AsciiDoc
> ==== ACCEPTED_ON_L1
> 
> The transaction was accepted on-chain.
> ```

On L1 or on Ethereum, I think (as Starknet is a chain as well)



_Code quote:_
```AsciiDoc
n-chain
```

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/703)* status: all files reviewed, 3 unresolved discussions (waiting on @EvyatarO)

___
*[`components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc` line 83 at r7](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-Nauw-KZ5UVuTvGc3j2t:-NavQemq70BCNUAMwZf8:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f8d6ead172597df06a9c604f427b4643e5601a17/components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc#L83)):*
<details><summary><i>Previously, EvyatarO (Evyatar) wrote…</i></summary><blockquote>

Sorry, we can delete this line if we removed the configurable_factor from the equation above.
</blockquote></details>

Done.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc` line 47 at r9](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-NavPdVy9af2Ssy3yjCb:-NavQqMQ9GJTxaVgR2ho:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6fed69d25f9a5a209a94a10203e5e6cab792b0ae/components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc#L47)):*
<details><summary><i>Previously, EvyatarO (Evyatar) wrote…</i></summary><blockquote>

It could also be Revert
</blockquote></details>

Done.
___
*[`components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc` line 57 at r9](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-NavPp_y9gqpxhb4CXcz:-NavR87F1ABX8dFpLqIH:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6fed69d25f9a5a209a94a10203e5e6cab792b0ae/components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc#L57)):*
<details><summary><i>Previously, EvyatarO (Evyatar) wrote…</i></summary><blockquote>

On L1 or on Ethereum, I think (as Starknet is a chain as well)
</blockquote></details>

Done.

**Review by EvyatarO — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, 1 of 2 files at r6, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/703#-:-NavW0dP6ocFzDyaiMXG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Pull request merged**
